2019-05-02 09:58:32,269 (7f7584987700) :  INFO (core:349) - Starting framework core - Version: 2.6.3, Build: ad6e397 (Thu Apr 04 06:47:07 UTC 2019)
2019-05-02 09:58:32,270 (7f7584987700) :  DEBUG (core:361) - Using the elevated policy
2019-05-02 09:58:32,270 (7f7584987700) :  DEBUG (core:365) - Extending whitelist: ['cgi', 'tempfile']
2019-05-02 09:58:32,271 (7f7584987700) :  DEBUG (core:450) - Starting runtime component.
2019-05-02 09:58:32,280 (7f7584987700) :  DEBUG (core:450) - Starting caching component.
2019-05-02 09:58:32,280 (7f7584987700) :  DEBUG (core:450) - Starting data component.
2019-05-02 09:58:32,280 (7f7584987700) :  DEBUG (core:450) - Starting networking component.
2019-05-02 09:58:32,292 (7f7584987700) :  DEBUG (networking:284) - Loaded HTTP cookies
2019-05-02 09:58:32,304 (7f7584987700) :  DEBUG (networking:452) - Setting the default network timeout to 20.0
2019-05-02 09:58:32,305 (7f7584987700) :  DEBUG (core:450) - Starting localization component.
2019-05-02 09:58:32,305 (7f7584987700) :  INFO (localization:409) - Setting the default locale to en-us
2019-05-02 09:58:32,324 (7f7584987700) :  DEBUG (localization:427) - Loaded en strings
2019-05-02 09:58:32,324 (7f7584987700) :  DEBUG (core:450) - Starting messaging component.
2019-05-02 09:58:32,324 (7f7584987700) :  DEBUG (core:450) - Starting debugging component.
2019-05-02 09:58:32,324 (7f7584987700) :  DEBUG (core:450) - Starting services component.
2019-05-02 09:58:32,325 (7f7584987700) :  DEBUG (core:450) - Starting myplex component.
2019-05-02 09:58:32,325 (7f7584987700) :  DEBUG (core:450) - Starting notifications component.
2019-05-02 09:58:32,730 (7f7584987700) :  DEBUG (accessor:68) - Creating a new model access point for provider com.plexapp.system in namespace 'metadata'
2019-05-02 09:58:32,795 (7f7584987700) :  DEBUG (runtime:1117) - Created a thread named 'load_all_services'
2019-05-02 09:58:32,795 (7f7574e79700) :  DEBUG (services:265) - Plug-in is not daemonized - loading services from system
2019-05-02 09:58:32,803 (7f7574e79700) :  DEBUG (networking:166) - Requesting 'http://127.0.0.1:32400/:/plugins/com.plexapp.system/messaging/function/X0J1bmRsZVNlcnZpY2U6QWxsU2VydmljZXM_/Y2VyZWFsMQoxCmxpc3QKMApyMAo_/Y2VyZWFsMQoxCmRpY3QKMApyMAo_'
2019-05-02 09:58:32,812 (7f7584987700) :  DEBUG (runtime:1117) - Created a thread named 'get_server_info'
2019-05-02 09:58:32,812 (7f7584987700) :  DEBUG (core:150) - Finished starting framework core
2019-05-02 09:58:32,812 (7f7584987700) :  DEBUG (core:560) - Loading plug-in code
2019-05-02 09:58:32,825 (7f755b7fe700) :  DEBUG (networking:166) - Requesting 'http://127.0.0.1:32400'
2019-05-02 09:58:32,904 (7f7584987700) :  DEBUG (core:566) - Finished loading plug-in code
2019-05-02 09:58:32,905 (7f7584987700) :  DEBUG (runtime:640) - Adding a prefix handler for 'System' ('/system')
2019-05-02 09:58:37,006 (7f7584987700) :  INFO (__init__:40) - Starting System ad6e397 (Thu Apr 04 06:47:07 UTC 2019)
2019-05-02 09:58:37,006 (7f7584987700) :  DEBUG (runtime:640) - Adding a prefix handler for 'Player' ('/player')
2019-05-02 09:58:37,056 (7f7584987700) :  INFO (datakit:93) - Loaded the dictionary file
2019-05-02 09:58:37,066 (7f7584987700) :  DEBUG (agentservice:48) - Starting the agent service
2019-05-02 09:58:37,472 (7f7584987700) :  DEBUG (accessor:68) - Creating a new model access point for provider com.plexapp.system in namespace 'metadata'
2019-05-02 09:58:37,511 (7f7584987700) :  DEBUG (bundleservice:69) - Starting the bundle service
2019-05-02 09:58:37,512 (7f7584987700) :  DEBUG (runtime:1117) - Created a thread named 'start'
2019-05-02 09:58:37,516 (7f7584987700) :  DEBUG (helpservice:14) - Starting the help service
2019-05-02 09:58:37,516 (7f7584987700) :  DEBUG (storeservice:198) - Starting the store service
2019-05-02 09:58:37,525 (7f7559dfb700) :  DEBUG (runtime:1117) - Created a thread named 'ensure_agent_info_exists_inner'
2019-05-02 09:58:37,535 (7f7584987700) :  DEBUG (runtime:1117) - Created a thread named 'start'
2019-05-02 09:58:37,535 (7f7584987700) :  DEBUG (installservice:30) - Starting the install service
2019-05-02 09:58:37,535 (7f75595fa700) :  DEBUG (networking:166) - Requesting 'http://127.0.0.1:32400'
2019-05-02 09:58:37,581 (7f7584987700) :  DEBUG (playerservice:12) - Starting the player service
2019-05-02 09:58:37,582 (7f7584987700) :  DEBUG (flagservice:13) - Starting the media flag service
2019-05-02 09:58:37,582 (7f7584987700) :  DEBUG (runtime:1117) - Created a thread named 'start'
2019-05-02 09:58:37,582 (7f7584987700) :  DEBUG (peerservice:141) - Starting the peer service
2019-05-02 09:58:37,586 (7f7553fff700) :  DEBUG (peerservice:164) - Fetching the current list of servers
2019-05-02 09:58:37,589 (7f7584987700) :  DEBUG (runtime:1117) - Created a thread named 'refresh_servers'
2019-05-02 09:58:37,590 (7f7553fff700) :  DEBUG (networking:166) - Requesting 'http://127.0.0.1:32400/servers'
2019-05-02 09:58:37,590 (7f7584987700) :  DEBUG (runtime:1150) - Scheduled a timed thread named 'refresh_servers'
2019-05-02 09:58:37,591 (7f7584987700) :  DEBUG (streamservice:18) - Starting the stream service
2019-05-02 09:58:37,591 (7f7584987700) :  CRITICAL (runtime:709) - Private handlers are no longer supported; couldn't register <bound method StreamService.token_handler of <streamservice.StreamService object at 0x7f7574452ed0>>
2019-05-02 09:58:37,595 (7f7559dfb700) :  DEBUG (runtime:1117) - Created a thread named 'ensure_agent_info_exists_inner'
2019-05-02 09:58:37,595 (7f7584987700) :  DEBUG (runtime:1150) - Scheduled a timed thread named 'invalidation_timer'
2019-05-02 09:58:37,596 (7f7584987700) :  DEBUG (proxyservice:12) - Starting the proxy service
2019-05-02 09:58:37,599 (7f7559dfb700) :  DEBUG (runtime:1117) - Created a thread named 'ensure_agent_info_exists_inner'
2019-05-02 09:58:37,599 (7f7584987700) :  DEBUG (runtime:1117) - Created a thread named 'update_attribution_flags_inner'
2019-05-02 09:58:37,599 (7f7584987700) :  INFO (core:611) - Started plug-in
2019-05-02 09:58:37,599 (7f7584987700) :  DEBUG (socketinterface:160) - Starting socket server
2019-05-02 09:58:37,601 (7f7559dfb700) :  DEBUG (runtime:1117) - Created a thread named 'ensure_agent_info_exists_inner'
2019-05-02 09:58:37,601 (7f7584987700) :  DEBUG (runtime:1117) - Created a thread named 'start'
2019-05-02 09:58:37,602 (7f7584987700) :  INFO (socketinterface:184) - Socket server started on port 33105
2019-05-02 09:58:37,602 (7f7584987700) :  INFO (pipeinterface:25) - Entering run loop
2019-05-02 09:58:37,602 (7f7584987700) :  DEBUG (runtime:717) - Handling request GET /:/prefixes
2019-05-02 09:58:37,603 (7f7559dfb700) :  DEBUG (runtime:1117) - Created a thread named 'ensure_agent_info_exists_inner'
2019-05-02 09:58:37,605 (7f7584987700) :  DEBUG (runtime:814) - Found route matching /:/prefixes
2019-05-02 09:58:37,607 (7f7584987700) :  DEBUG (runtime:924) - Response: [200] MediaContainer, 486 bytes
2019-05-02 09:58:37,609 (7f7559dfb700) :  DEBUG (runtime:1117) - Created a thread named 'ensure_agent_info_exists_inner'
2019-05-02 09:58:37,610 (7f7551ffb700) :  DEBUG (runtime:717) - Handling request GET /system/agents
2019-05-02 09:58:37,613 (7f7559dfb700) :  DEBUG (runtime:1117) - Created a thread named 'ensure_agent_info_exists_inner'
2019-05-02 09:58:37,623 (7f7559dfb700) :  DEBUG (runtime:1117) - Created a thread named 'ensure_agent_info_exists_inner'
2019-05-02 09:58:37,705 (7f7559dfb700) :  DEBUG (runtime:1117) - Created a thread named 'ensure_agent_info_exists_inner'
2019-05-02 09:58:37,718 (7f7559dfb700) :  DEBUG (runtime:1117) - Created a thread named 'ensure_agent_info_exists_inner'
2019-05-02 09:58:37,740 (7f7559dfb700) :  DEBUG (runtime:1117) - Created a thread named 'ensure_agent_info_exists_inner'
2019-05-02 09:58:37,753 (7f7559dfb700) :  DEBUG (runtime:1117) - Created a thread named 'ensure_agent_info_exists_inner'
2019-05-02 09:58:37,758 (7f7551ffb700) :  DEBUG (runtime:814) - Found route matching /system/agents
2019-05-02 09:58:37,758 (7f7559dfb700) :  DEBUG (runtime:1117) - Created a thread named 'ensure_agent_info_exists_inner'
2019-05-02 09:58:38,324 (7f755b7fe700) :  DEBUG (core:538) - Machine identifier is 3e7b7fe94c75e0be03ba9545393f1604f763ce60
2019-05-02 09:58:38,332 (7f7553fff700) :  DEBUG (peerservice:171) - Refreshing local server
2019-05-02 09:58:38,340 (7f7553fff700) :  DEBUG (peerservice:189) - Updating servers (True/False True/True/True)
2019-05-02 09:58:38,340 (7f7553fff700) :  DEBUG (peerservice:198) - Found 1 servers
2019-05-02 09:58:38,340 (7f7553fff700) :  DEBUG (peerservice:230) - Creating new server 4cc082ea20e3 (3e7b7fe94c75e0be03ba9545393f1604f763ce60)
2019-05-02 09:58:38,332 (7f75595fa700) :  DEBUG (core:521) - Attribute 'machineIdentifier' set to '3e7b7fe94c75e0be03ba9545393f1604f763ce60'
2019-05-02 09:58:38,344 (7f75595fa700) :  DEBUG (networking:166) - Requesting 'http://127.0.0.1:32400'
2019-05-02 09:58:38,364 (7f755b7fe700) :  DEBUG (core:539) - Server version is 1.15.3.876-ad6e39743
2019-05-02 09:58:38,375 (7f7553fff700) :  DEBUG (networking:166) - Requesting 'http://127.0.0.1:32400/library/sections'
2019-05-02 09:58:38,427 (7f75595fa700) :  DEBUG (core:521) - Attribute 'platformVersion' set to '4.9.0-8-amd64'
2019-05-02 09:58:38,443 (7f7553fff700) :  DEBUG (networking:166) - Requesting 'http://127.0.0.1:32400/channels/all'
2019-05-02 09:58:38,444 (7f75507f8700) :  DEBUG (runtime:717) - Handling request GET /:/plugins/com.plexapp.system/messaging/function/X0J1bmRsZVNlcnZpY2U6QWxsU2VydmljZXM_/Y2VyZWFsMQoxCmxpc3QKMApyMAo_/Y2VyZWFsMQoxCmRpY3QKMApyMAo_
2019-05-02 09:58:38,591 (7f75595fa700) :  DEBUG (networking:166) - Requesting 'https://plugins.plex.tv/apps/all.json?frameworkVersion=2.6.3&machineIdentifier=3e7b7fe94c75e0be03ba9545393f1604f763ce60&os=Linux&osVersion=4.9.0-8-amd64&cpu=i386&serverVersion=1.15.3.876-ad6e39743&systemRevision=ad6e397'
2019-05-02 09:58:38,621 (7f755b7fe700) :  DEBUG (peerservice:176) - Background-refreshing remote servers
2019-05-02 09:58:38,622 (7f755b7fe700) :  DEBUG (peerservice:189) - Updating servers (False/True True/True/True)
2019-05-02 09:58:38,623 (7f755b7fe700) :  DEBUG (peerservice:198) - Found 1 servers
2019-05-02 09:58:38,627 (7f7553fff700) :  DEBUG (runtime:1117) - Created a thread named 'background_refresh'
2019-05-02 09:58:38,793 (7f75507f8700) :  DEBUG (runtime:814) - Found route matching /:/plugins/com.plexapp.system/messaging/function/X0J1bmRsZVNlcnZpY2U6QWxsU2VydmljZXM_/Y2VyZWFsMQoxCmxpc3QKMApyMAo_/Y2VyZWFsMQoxCmRpY3QKMApyMAo_
2019-05-02 09:58:39,102 (7f7559dfb700) :  DEBUG (runtime:1117) - Created a thread named 'remove_unavailable_agents'
2019-05-02 09:58:39,108 (7f7558df9700) :  DEBUG (flagservice:46) - Started the media flag service
2019-05-02 09:58:39,164 (7f7559dfb700) :  DEBUG (bundleservice:85) - Started the bundle service
2019-05-02 09:58:39,169 (7f75517fa700) :  INFO (agentservice:121) - Agent info: {'com.plexapp.agents.fanarttv': [{'media_types': ['Movie'], 'accepts_from': None, 'fallback_agent': None, 'contributes_to': ['com.plexapp.agents.imdb', 'com.plexapp.agents.themoviedb'], 'has_attribution': True, 'languages': ['xn'], 'persist_stored_files': True, 'version': 0, 'primary_provider': False, 'prefs': True, 'name': 'Fanart.tv'}, {'media_types': ['TV_Show'], 'accepts_from': None, 'fallback_agent': None, 'contributes_to': ['com.plexapp.agents.thetvdb', 'com.plexapp.agents.themoviedb'], 'has_attribution': True, 'languages': ['xn'], 'persist_stored_files': True, 'version': 0, 'primary_provider': False, 'prefs': True, 'name': 'Fanart.tv'}, {'media_types': ['Artist'], 'accepts_from': None, 'fallback_agent': None, 'contributes_to': ['com.plexapp.agents.lastfm'], 'has_attribution': True, 'languages': ['xn'], 'persist_stored_files': True, 'version': 0, 'primary_provider': False, 'prefs': True, 'name': 'Fanart.tv'}, {'media_types': ['Album'], 'accepts_from': None, 'fallback_agent': None, 'contributes_to': ['com.plexapp.agents.lastfm'], 'has_attribution': True, 'languages': ['xn'], 'persist_stored_files': True, 'version': 0, 'primary_provider': False, 'prefs': True, 'name': 'Fanart.tv'}], 'com.plexapp.agents.none': [{'media_types': ['Movie'], 'accepts_from': None, 'fallback_agent': None, 'contributes_to': None, 'has_attribution': False, 'languages': ['xn'], 'persist_stored_files': True, 'version': 0, 'primary_provider': True, 'prefs': False, 'name': 'Personal Media'}, {'media_types': ['TV_Show'], 'accepts_from': None, 'fallback_agent': None, 'contributes_to': None, 'has_attribution': False, 'languages': ['xn'], 'persist_stored_files': True, 'version': 0, 'primary_provider': True, 'prefs': False, 'name': 'Personal Media Shows'}, {'media_types': ['Artist'], 'accepts_from': None, 'fallback_agent': None, 'contributes_to': None, 'has_attribution': False, 'languages': ['xn'], 'persist_stored_files': True, 'version': 0, 'primary_provider': True, 'prefs': False, 'name': 'Personal Media Artists'}, {'media_types': ['Album'], 'accepts_from': None, 'fallback_agent': None, 'contributes_to': None, 'has_attribution': False, 'languages': ['xn'], 'persist_stored_files': True, 'version': 0, 'primary_provider': True, 'prefs': False, 'name': 'Personal Media Albums'}, {'media_types': ['Photo'], 'accepts_from': None, 'fallback_agent': None, 'contributes_to': None, 'has_attribution': False, 'languages': ['en', 'ar', 'bg', 'ca', 'cs', 'cy', 'da', 'de', 'el', 'es', 'et', 'fa', 'fi', 'fr', 'he', 'hi', 'hr', 'ht', 'hu', 'id', 'it', 'ja', 'ko', 'lt', 'lv', 'ms', 'mt', 'nl', 'no', 'pl', 'pt', 'ro', 'ru', 'sk', 'sv', 'sl', 'sr', 'th', 'tr', 'uk', 'ur', 'vi', 'zh', 'xn'], 'persist_stored_files': True, 'version': 0, 'primary_provider': True, 'prefs': False, 'name': 'Photos'}], 'com.plexapp.agents.plexmusic': [{'media_types': ['Artist'], 'accepts_from': None, 'fallback_agent': None, 'contributes_to': ['com.plexapp.agents.localmedia'], 'has_attribution': True, 'languages': ['en', 'ar', 'bg', 'zh', 'hr', 'cs', 'da', 'nl', 'fi', 'fr', 'de', 'el', 'hu', 'id', 'it', 'ja', 'ko', 'nn', 'pl', 'pt', 'ro', 'ru', 'sr', 'sk', 'es', 'sv', 'th', 'tr', 'vi'], 'persist_stored_files': True, 'version': 0, 'primary_provider': True, 'prefs': True, 'name': 'Plex Premium Music'}, {'media_types': ['Album'], 'accepts_from': None, 'fallback_agent': None, 'contributes_to': ['com.plexapp.agents.localmedia'], 'has_attribution': True, 'languages': ['en', 'ar', 'bg', 'zh', 'hr', 'cs', 'da', 'nl', 'fi', 'fr', 'de', 'el', 'hu', 'id', 'it', 'ja', 'ko', 'nn', 'pl', 'pt', 'ro', 'ru', 'sr', 'sk', 'es', 'sv', 'th', 'tr', 'vi'], 'persist_stored_files': True, 'version': 0, 'primary_provider': True, 'prefs': True, 'name': 'Plex Premium Music'}], 'com.plexapp.agents.htbackdrops': [{'media_types': ['Artist'], 'accepts_from': None, 'fallback_agent': None, 'contributes_to': ['com.plexapp.agents.lastfm'], 'has_attribution': True, 'languages': ['ab', 'aa', 'af', 'ak', 'sq', 'am', 'ar', 'an', 'hy', 'as', 'av', 'ae', 'ay', 'az', 'bm', 'ba', 'eu', 'be', 'bn', 'bh', 'bi', 'bs', 'pb', 'br', 'bg', 'my', 'ca', 'ch', 'ce', 'ny', 'zh', 'cu', 'cv', 'kw', 'co', 'cr', 'hr', 'cs', 'da', 'dv', 'nl', 'dz', 'en', 'eo', 'et', 'ee', 'fo', 'fj', 'fi', 'fr', 'fy', 'ff', 'gd', 'gl', 'lg', 'ka', 'de', 'el', 'gn', 'gu', 'ht', 'ha', 'he', 'hz', 'hi', 'ho', 'hu', 'is', 'io', 'ig', 'id', 'ia', 'ie', 'iu', 'ik', 'ga', 'it', 'ja', 'jv', 'kl', 'kn', 'kr', 'ks', 'kk', 'km', 'ki', 'rw', 'ky', 'kv', 'kg', 'ko', 'kj', 'ku', 'lo', 'la', 'lv', 'li', 'ln', 'lt', 'lu', 'lb', 'mk', 'mg', 'ms', 'ml', 'mt', 'gv', 'mi', 'mr', 'mh', 'mo', 'mn', 'na', 'nv', 'ng', 'ne', 'xn', 'nd', 'no', 'nb', 'nn', 'oc', 'oj', 'or', 'om', 'os', 'pi', 'pa', 'fa', 'pl', 'pt', 'ps', 'qu', 'rm', 'ro', 'rn', 'ru', 'se', 'sm', 'sg', 'sa', 'sc', 'sr', 'sn', 'ii', 'sd', 'si', 'sk', 'sl', 'so', 'st', 'nr', 'es', 'su', 'sw', 'ss', 'sv', 'tl', 'ty', 'tg', 'ta', 'tt', 'te', 'th', 'bo', 'ti', 'to', 'ts', 'tn', 'tr', 'tk', 'tw', 'ug', 'uk', 'ur', 'uz', 've', 'vi', 'vo', 'wa', 'cy', 'wo', 'xh', 'yi', 'yo', 'za', 'zu'], 'persist_stored_files': True, 'version': 0, 'primary_provider': False, 'prefs': False, 'name': 'Home Theater Backdrops'}], 'com.plexapp.agents.imdb': [{'media_types': ['Movie'], 'accepts_from': ['com.plexapp.agents.localmedia'], 'fallback_agent': None, 'contributes_to': ['com.plexapp.agents.themoviedb'], 'has_attribution': True, 'languages': ['en', 'sv', 'fr', 'es', 'nl', 'de', 'it', 'da', 'ar', 'ca', 'zh', 'cs', 'et', 'fi', 'el', 'he', 'hi', 'hu', 'id', 'ja', 'ko', 'lv', 'no', 'fa', 'pl', 'pt', 'ro', 'ru', 'sk', 'th', 'tr', 'uk', 'vi'], 'persist_stored_files': True, 'version': 0, 'primary_provider': True, 'prefs': True, 'name': 'Plex Movie'}], 'com.plexapp.agents.lyricfind': [{'media_types': ['Album'], 'accepts_from': None, 'fallback_agent': None, 'contributes_to': ['com.plexapp.agents.plexmusic', 'com.plexapp.agents.localmedia', 'com.plexapp.agents.lastfm'], 'has_attribution': True, 'languages': ['xn'], 'persist_stored_files': True, 'version': 0, 'primary_provider': False, 'prefs': False, 'name': 'LyricFind'}], 'com.plexapp.agents.thetvdb': [{'media_types': ['TV_Show'], 'accepts_from': None, 'fallback_agent': None, 'contributes_to': None, 'has_attribution': True, 'languages': ['en', 'fr', 'zh', 'sv', 'no', 'da', 'fi', 'nl', 'de', 'it', 'es', 'pl', 'hu', 'el', 'tr', 'ru', 'he', 'ja', 'pt', 'cs', 'ko', 'sl', 'hr'], 'persist_stored_files': True, 'version': 0, 'primary_provider': True, 'prefs': True, 'name': 'TheTVDB'}], 'com.plexapp.agents.localmedia': [{'media_types': ['Movie'], 'accepts_from': None, 'fallback_agent': None, 'contributes_to': ['com.plexapp.agents.imdb', 'com.plexapp.agents.none'], 'has_attribution': False, 'languages': ['xn'], 'persist_stored_files': False, 'version': 0, 'primary_provider': False, 'prefs': True, 'name': 'Local Media Assets (Movies)'}, {'media_types': ['TV_Show'], 'accepts_from': None, 'fallback_agent': None, 'contributes_to': ['com.plexapp.agents.thetvdb', 'com.plexapp.agents.none'], 'has_attribution': False, 'languages': ['xn'], 'persist_stored_files': False, 'version': 0, 'primary_provider': False, 'prefs': True, 'name': 'Local Media Assets (TV)'}, {'media_types': ['Artist'], 'accepts_from': None, 'fallback_agent': None, 'contributes_to': ['com.plexapp.agents.discogs', 'com.plexapp.agents.lastfm', 'com.plexapp.agents.plexmusic', 'com.plexapp.agents.none'], 'has_attribution': False, 'languages': ['xn'], 'persist_stored_files': False, 'version': 0, 'primary_provider': False, 'prefs': True, 'name': 'Local Media Assets (Artists)'}, {'media_types': ['Artist'], 'accepts_from': None, 'fallback_agent': None, 'contributes_to': ['com.plexapp.agents.plexmusic'], 'has_attribution': False, 'languages': ['xn'], 'persist_stored_files': False, 'version': 2, 'primary_provider': False, 'prefs': True, 'name': 'Local Media Assets (Artists)'}, {'media_types': ['Album'], 'accepts_from': None, 'fallback_agent': None, 'contributes_to': ['com.plexapp.agents.discogs', 'com.plexapp.agents.lastfm', 'com.plexapp.agents.plexmusic', 'com.plexapp.agents.none'], 'has_attribution': False, 'languages': ['xn'], 'persist_stored_files': False, 'version': 0, 'primary_provider': False, 'prefs': True, 'name': 'Local Media Assets (Albums)'}], 'com.plexapp.agents.plexthememusic': [{'media_types': ['TV_Show'], 'accepts_from': None, 'fallback_agent': None, 'contributes_to': ['com.plexapp.agents.thetvdb', 'com.plexapp.agents.thetvdbdvdorder', 'com.plexapp.agents.themoviedb'], 'has_attribution': False, 'languages': ['xn'], 'persist_stored_files': True, 'version': 0, 'primary_provider': False, 'prefs': False, 'name': 'Plex Theme Music'}], 'com.plexapp.agents.themoviedb': [{'media_types': ['Movie'], 'accepts_from': ['com.plexapp.agents.localmedia'], 'fallback_agent': None, 'contributes_to': None, 'has_attribution': True, 'languages': ['en', 'cs', 'da', 'de', 'el', 'es', 'fi', 'fr', 'he', 'hr', 'hu', 'it', 'lv', 'lt', 'nl', 'no', 'pl', 'pt', 'ru', 'sk', 'sv', 'th', 'tr', 'vi', 'zh', 'ko'], 'persist_stored_files': True, 'version': 0, 'primary_provider': True, 'prefs': True, 'name': 'The Movie Database'}, {'media_types': ['TV_Show'], 'accepts_from': ['com.plexapp.agents.localmedia', 'com.plexapp.agents.thetvdb'], 'fallback_agent': None, 'contributes_to': ['com.plexapp.agents.thetvdb'], 'has_attribution': True, 'languages': ['en', 'cs', 'da', 'de', 'el', 'es', 'fi', 'fr', 'he', 'hr', 'hu', 'it', 'lv', 'lt', 'nl', 'no', 'pl', 'pt', 'ru', 'sk', 'sv', 'th', 'tr', 'vi', 'zh', 'ko'], 'persist_stored_files': True, 'version': 0, 'primary_provider': True, 'prefs': True, 'name': 'The Movie Database'}], 'com.plexapp.agents.movieposterdb': [{'media_types': ['Movie'], 'accepts_from': None, 'fallback_agent': None, 'contributes_to': ['com.plexapp.agents.imdb'], 'has_attribution': True, 'languages': ['xn'], 'persist_stored_files': True, 'version': 0, 'primary_provider': False, 'prefs': False, 'name': 'CineMaterial'}], 'com.plexapp.agents.opensubtitles': [{'media_types': ['Movie'], 'accepts_from': None, 'fallback_agent': None, 'contributes_to': ['com.plexapp.agents.imdb'], 'has_attribution': False, 'languages': ['xn'], 'persist_stored_files': True, 'version': 0, 'primary_provider': False, 'prefs': True, 'name': 'OpenSubtitles.org'}, {'media_types': ['TV_Show'], 'accepts_from': None, 'fallback_agent': None, 'contributes_to': ['com.plexapp.agents.thetvdb'], 'has_attribution': False, 'languages': ['xn'], 'persist_stored_files': True, 'version': 0, 'primary_provider': False, 'prefs': True, 'name': 'OpenSubtitles.org'}], 'com.plexapp.agents.lastfm': [{'media_types': ['Artist'], 'accepts_from': None, 'fallback_agent': None, 'contributes_to': None, 'has_attribution': True, 'languages': ['en', 'sv', 'fr', 'es', 'de', 'pl', 'it', 'pt', 'ja', 'tr', 'ru', 'zh'], 'persist_stored_files': True, 'version': 0, 'primary_provider': True, 'prefs': True, 'name': 'Last.fm'}, {'media_types': ['Album'], 'accepts_from': None, 'fallback_agent': None, 'contributes_to': None, 'has_attribution': True, 'languages': ['en', 'sv', 'fr', 'es', 'de', 'pl', 'it', 'pt', 'ja', 'tr', 'ru', 'zh'], 'persist_stored_files': True, 'version': 0, 'primary_provider': True, 'prefs': True, 'name': 'Last.fm'}]}
2019-05-02 09:58:39,216 (7f75517fa700) :  INFO (datakit:131) - Saved the dictionary file
2019-05-02 09:58:39,415 (7f7551ffb700) :  DEBUG (runtime:924) - Response: [200] MediaContainer, 9036 bytes
2019-05-02 09:58:39,620 (7f75507f8700) :  DEBUG (runtime:924) - Response: [200] str, 59980 bytes
2019-05-02 09:58:40,143 (7f7574e79700) :  DEBUG (services:362) - Loaded services
2019-05-02 09:58:40,160 (7f75595fa700) :  DEBUG (preferences:258) - Loaded preferences from DefaultPrefs.json
2019-05-02 09:58:40,164 (7f75595fa700) :  DEBUG (preferences:178) - Loaded the user preferences for com.plexapp.system
2019-05-02 09:58:40,164 (7f75595fa700) :  INFO (storeservice:495) - No beta plugins.
2019-05-02 09:58:40,181 (7f755bfff700) :  DEBUG (services:438) - No shared code to load
2019-05-02 09:58:40,195 (7f75595fa700) :  INFO (storeservice:334) - Starting automatic update thread
2019-05-02 09:58:40,208 (7f75595fa700) :  DEBUG (runtime:1150) - Scheduled a timed thread named 'auto_update_thread'
2019-05-02 09:58:40,209 (7f75595fa700) :  DEBUG (storeservice:328) - Started the store service
2019-05-02 09:58:42,778 (7f75595fa700) :  DEBUG (runtime:717) - Handling request GET /system/messaging/clear_events/com.plexapp.agents.imdb
2019-05-02 09:58:42,963 (7f7574e79700) :  DEBUG (runtime:717) - Handling request GET /system/notify/serverUpdated?host=127.0.0.1
2019-05-02 09:58:43,352 (7f75507f8700) :  DEBUG (runtime:717) - Handling request GET /:/plugins/com.plexapp.system/resourceHashes
2019-05-02 09:58:43,382 (7f75507f8700) :  DEBUG (runtime:814) - Found route matching /:/plugins/com.plexapp.system/resourceHashes
2019-05-02 09:58:43,410 (7f75507f8700) :  DEBUG (networking:166) - Requesting 'http://resources-cdn.plexapp.com/hashes.json'
2019-05-02 09:58:43,498 (7f75595fa700) :  DEBUG (runtime:814) - Found route matching /system/messaging/clear_events/com.plexapp.agents.imdb
2019-05-02 09:58:43,500 (7f75595fa700) :  DEBUG (runtime:924) - Response: [200] str, 0 bytes
2019-05-02 09:58:43,518 (7f7574e79700) :  DEBUG (runtime:814) - Found route matching /system/notify/serverUpdated
2019-05-02 09:58:43,519 (7f7574e79700) :  DEBUG (peerservice:386) - Handling server update notification (127.0.0.1)
2019-05-02 09:58:43,519 (7f7574e79700) :  DEBUG (peerservice:189) - Updating servers (False/False True/True/True)
2019-05-02 09:58:43,519 (7f7574e79700) :  DEBUG (peerservice:164) - Fetching the current list of servers
2019-05-02 09:58:43,519 (7f7574e79700) :  DEBUG (networking:166) - Requesting 'http://127.0.0.1:32400/servers'
2019-05-02 09:58:43,575 (7f7574e79700) :  DEBUG (peerservice:198) - Found 1 servers
2019-05-02 09:58:43,576 (7f7574e79700) :  DEBUG (peerservice:214) - Ignoring 3e7b7fe94c75e0be03ba9545393f1604f763ce60 because host != 127.0.0.1 (172.18.0.10)
2019-05-02 09:58:43,576 (7f7574e79700) :  DEBUG (networking:166) - Requesting 'http://127.0.0.1:32400/library/sections'
2019-05-02 09:58:43,592 (7f75507f8700) :  DEBUG (runtime:924) - Response: [200] str, 13276 bytes
2019-05-02 09:58:43,860 (7f75595fa700) :  DEBUG (runtime:717) - Handling request GET /:/plugins/com.plexapp.system/messaging/function/X0J1bmRsZVNlcnZpY2U6QWxsU2VydmljZXM_/Y2VyZWFsMQoxCmxpc3QKMApyMAo_/Y2VyZWFsMQoxCmRpY3QKMApyMAo_
2019-05-02 09:58:44,060 (7f7574e79700) :  DEBUG (networking:166) - Requesting 'http://127.0.0.1:32400/channels/all'
2019-05-02 09:58:44,216 (7f75595fa700) :  DEBUG (runtime:814) - Found route matching /:/plugins/com.plexapp.system/messaging/function/X0J1bmRsZVNlcnZpY2U6QWxsU2VydmljZXM_/Y2VyZWFsMQoxCmxpc3QKMApyMAo_/Y2VyZWFsMQoxCmRpY3QKMApyMAo_
2019-05-02 09:58:45,012 (7f7574e79700) :  DEBUG (runtime:924) - Response: [200] str, 0 bytes
2019-05-02 09:58:46,310 (7f7553fff700) :  INFO (datakit:131) - Saved the dictionary file
2019-05-02 09:58:46,853 (7f75595fa700) :  DEBUG (runtime:924) - Response: [200] str, 59980 bytes
2019-05-02 09:58:46,867 (7f75595fa700) :  DEBUG (runtime:717) - Handling request GET /:/plugins/com.plexapp.system/messaging/function/X0FnZW50U2VydmljZTpVcGRhdGVJbmZv/Y2VyZWFsMQoxCmxpc3QKMApyMAo_/Y2VyZWFsMQo3CmRpY3QKbGlzdApkaWN0Cmxpc3QKbGlzdApsaXN0Cmxpc3QKMgpzMjMKY29tLnBsZXhhcHAuYWdlbnRzLmltZGJzMTAKaWRlbnRpZmllcnIxCnMxMAphZ2VudF9pbmZvMQpyMgoxMApyMwpzMTEKbWVkaWFfdHlwZXNyNApzMTIKYWNjZXB0c19mcm9tbnMxNApmYWxsYmFja19hZ2VudHI1CnMxNApjb250cmlidXRlc190b3I2CnM5Cmxhbmd1YWdlc2IxczIwCnBlcnNpc3Rfc3RvcmVkX2ZpbGVzaTAKczcKdmVyc2lvbmIxczE2CnByaW1hcnlfcHJvdmlkZXJiMXM1CnByZWZzczEwClBsZXggTW92aWVzNApuYW1lMQpzNQpNb3ZpZTEKczI5CmNvbS5wbGV4YXBwLmFnZW50cy5sb2NhbG1lZGlhMQpzMjkKY29tLnBsZXhhcHAuYWdlbnRzLnRoZW1vdmllZGIzMwpzMgplbnMyCnN2czIKZnJzMgplc3MyCm5sczIKZGVzMgppdHMyCmRhczIKYXJzMgpjYXMyCnpoczIKY3NzMgpldHMyCmZpczIKZWxzMgpoZXMyCmhpczIKaHVzMgppZHMyCmphczIKa29zMgpsdnMyCm5vczIKZmFzMgpwbHMyCnB0czIKcm9zMgpydXMyCnNrczIKdGhzMgp0cnMyCnVrczIKdmlyMAo_
2019-05-02 09:58:46,868 (7f75595fa700) :  DEBUG (runtime:814) - Found route matching /:/plugins/com.plexapp.system/messaging/function/X0FnZW50U2VydmljZTpVcGRhdGVJbmZv/Y2VyZWFsMQoxCmxpc3QKMApyMAo_/Y2VyZWFsMQo3CmRpY3QKbGlzdApkaWN0Cmxpc3QKbGlzdApsaXN0Cmxpc3QKMgpzMjMKY29tLnBsZXhhcHAuYWdlbnRzLmltZGJzMTAKaWRlbnRpZmllcnIxCnMxMAphZ2VudF9pbmZvMQpyMgoxMApyMwpzMTEKbWVkaWFfdHlwZXNyNApzMTIKYWNjZXB0c19mcm9tbnMxNApmYWxsYmFja19hZ2VudHI1CnMxNApjb250cmlidXRlc190b3I2CnM5Cmxhbmd1YWdlc2IxczIwCnBlcnNpc3Rfc3RvcmVkX2ZpbGVzaTAKczcKdmVyc2lvbmIxczE2CnByaW1hcnlfcHJvdmlkZXJiMXM1CnByZWZzczEwClBsZXggTW92aWVzNApuYW1lMQpzNQpNb3ZpZTEKczI5CmNvbS5wbGV4YXBwLmFnZW50cy5sb2NhbG1lZGlhMQpzMjkKY29tLnBsZXhhcHAuYWdlbnRzLnRoZW1vdmllZGIzMwpzMgplbnMyCnN2czIKZnJzMgplc3MyCm5sczIKZGVzMgppdHMyCmRhczIKYXJzMgpjYXMyCnpoczIKY3NzMgpldHMyCmZpczIKZWxzMgpoZXMyCmhpczIKaHVzMgppZHMyCmphczIKa29zMgpsdnMyCm5vczIKZmFzMgpwbHMyCnB0czIKcm9zMgpydXMyCnNrczIKdGhzMgp0cnMyCnVrczIKdmlyMAo_
2019-05-02 09:58:46,873 (7f75595fa700) :  INFO (agentservice:167) - Receiving agent info from com.plexapp.agents.imdb: [{'media_types': ['Movie'], 'primary_provider': True, 'fallback_agent': None, 'contributes_to': ['com.plexapp.agents.themoviedb'], 'languages': ['en', 'sv', 'fr', 'es', 'nl', 'de', 'it', 'da', 'ar', 'ca', 'zh', 'cs', 'et', 'fi', 'el', 'he', 'hi', 'hu', 'id', 'ja', 'ko', 'lv', 'no', 'fa', 'pl', 'pt', 'ro', 'ru', 'sk', 'th', 'tr', 'uk', 'vi'], 'persist_stored_files': True, 'version': 0, 'accepts_from': ['com.plexapp.agents.localmedia'], 'prefs': True, 'name': 'Plex Movie'}]
2019-05-02 09:58:46,980 (7f75595fa700) :  DEBUG (runtime:924) - Response: [200] str, 16 bytes
2019-05-02 09:58:52,012 (7f7553fff700) :  INFO (datakit:131) - Saved the dictionary file
2019-05-02 09:59:40,241 (7f755bfff700) :  DEBUG (runtime:1156) - Starting timed thread named 'auto_update_thread'
2019-05-02 09:59:40,257 (7f755bfff700) :  INFO (storeservice:356) - Starting automatic update check
2019-05-02 09:59:40,310 (7f755bfff700) :  DEBUG (runtime:1117) - Created a thread named 'remove_unavailable_agents'
2019-05-02 09:59:40,478 (7f755bfff700) :  DEBUG (networking:166) - Requesting 'https://plugins.plex.tv/apps/all.json?frameworkVersion=2.6.3&machineIdentifier=3e7b7fe94c75e0be03ba9545393f1604f763ce60&os=Linux&osVersion=4.9.0-8-amd64&cpu=i386&serverVersion=1.15.3.876-ad6e39743&systemRevision=ad6e397'
2019-05-02 09:59:41,176 (7f755bfff700) :  INFO (storeservice:495) - No beta plugins.
2019-05-02 09:59:41,190 (7f755bfff700) :  INFO (storeservice:531) - 'Services' plug-in [com.plexapp.system.services] is up to date (62fcf1f)
2019-05-02 09:59:41,191 (7f755bfff700) :  INFO (storeservice:362) - All plug-ins are up to date
2019-05-02 09:59:41,197 (7f755bfff700) :  DEBUG (runtime:1150) - Scheduled a timed thread named 'auto_update_thread'
2019-05-02 09:59:45,463 (7f75595fa700) :  INFO (datakit:131) - Saved the dictionary file
2019-05-02 10:00:37,645 (7f75537fe700) :  DEBUG (runtime:1156) - Starting timed thread named 'refresh_servers'
2019-05-02 10:00:37,693 (7f75537fe700) :  DEBUG (peerservice:164) - Fetching the current list of servers
2019-05-02 10:00:37,795 (7f75537fe700) :  DEBUG (networking:166) - Requesting 'http://127.0.0.1:32400/servers'
2019-05-02 10:00:38,506 (7f75537fe700) :  DEBUG (peerservice:171) - Refreshing local server
2019-05-02 10:00:38,506 (7f75537fe700) :  DEBUG (peerservice:189) - Updating servers (True/False True/True/True)
2019-05-02 10:00:38,510 (7f75537fe700) :  DEBUG (peerservice:198) - Found 1 servers
2019-05-02 10:00:38,511 (7f75537fe700) :  DEBUG (peerservice:233) - Updating existing server 4cc082ea20e3 (3e7b7fe94c75e0be03ba9545393f1604f763ce60)
2019-05-02 10:00:38,512 (7f75537fe700) :  DEBUG (networking:166) - Requesting 'http://127.0.0.1:32400/library/sections'
2019-05-02 10:00:38,530 (7f75537fe700) :  DEBUG (networking:166) - Requesting 'http://127.0.0.1:32400/channels/all'
2019-05-02 10:00:38,537 (7f75537fe700) :  DEBUG (runtime:1117) - Created a thread named 'background_refresh'
2019-05-02 10:00:38,537 (7f75595fa700) :  DEBUG (peerservice:176) - Background-refreshing remote servers
2019-05-02 10:00:38,537 (7f75595fa700) :  DEBUG (peerservice:189) - Updating servers (False/True True/True/True)
2019-05-02 10:00:38,537 (7f75595fa700) :  DEBUG (peerservice:198) - Found 1 servers
2019-05-02 10:58:37,697 (7f75527fc700) :  DEBUG (runtime:1156) - Starting timed thread named 'invalidation_timer'
2019-05-02 14:07:33,262 (7f7553fff700) :  DEBUG (runtime:1156) - Starting timed thread named 'auto_update_thread'
2019-05-02 14:07:33,334 (7f7553fff700) :  INFO (storeservice:356) - Starting automatic update check
2019-05-02 14:07:33,391 (7f7553fff700) :  DEBUG (runtime:1117) - Created a thread named 'remove_unavailable_agents'
2019-05-02 14:07:33,638 (7f7553fff700) :  DEBUG (networking:166) - Requesting 'https://plugins.plex.tv/apps/all.json?frameworkVersion=2.6.3&machineIdentifier=3e7b7fe94c75e0be03ba9545393f1604f763ce60&os=Linux&osVersion=4.9.0-8-amd64&cpu=i386&serverVersion=1.15.3.876-ad6e39743&systemRevision=ad6e397'
2019-05-02 14:07:34,068 (7f7553fff700) :  INFO (storeservice:495) - No beta plugins.
2019-05-02 14:07:34,077 (7f7553fff700) :  INFO (storeservice:531) - 'Services' plug-in [com.plexapp.system.services] is up to date (62fcf1f)
2019-05-02 14:07:34,078 (7f7553fff700) :  INFO (storeservice:362) - All plug-ins are up to date
2019-05-02 14:07:34,092 (7f7553fff700) :  DEBUG (runtime:1150) - Scheduled a timed thread named 'auto_update_thread'
2019-05-02 14:07:38,549 (7f75595fa700) :  INFO (datakit:131) - Saved the dictionary file
2019-05-02 18:13:05,175 (7f75527fc700) :  DEBUG (runtime:1156) - Starting timed thread named 'auto_update_thread'
2019-05-02 18:13:05,225 (7f75527fc700) :  INFO (storeservice:356) - Starting automatic update check
2019-05-02 18:13:05,267 (7f75527fc700) :  DEBUG (runtime:1117) - Created a thread named 'remove_unavailable_agents'
2019-05-02 18:13:05,525 (7f75527fc700) :  DEBUG (networking:166) - Requesting 'https://plugins.plex.tv/apps/all.json?frameworkVersion=2.6.3&machineIdentifier=3e7b7fe94c75e0be03ba9545393f1604f763ce60&os=Linux&osVersion=4.9.0-8-amd64&cpu=i386&serverVersion=1.15.3.876-ad6e39743&systemRevision=ad6e397'
2019-05-02 18:13:06,117 (7f75527fc700) :  INFO (storeservice:495) - No beta plugins.
2019-05-02 18:13:06,124 (7f75527fc700) :  INFO (storeservice:531) - 'Services' plug-in [com.plexapp.system.services] is up to date (62fcf1f)
2019-05-02 18:13:06,125 (7f75527fc700) :  INFO (storeservice:362) - All plug-ins are up to date
2019-05-02 18:13:06,127 (7f75527fc700) :  DEBUG (runtime:1150) - Scheduled a timed thread named 'auto_update_thread'
2019-05-02 18:13:10,413 (7f7553fff700) :  INFO (datakit:131) - Saved the dictionary file
2019-05-03 00:35:20,212 (7f75595fa700) :  DEBUG (runtime:1156) - Starting timed thread named 'auto_update_thread'
2019-05-03 00:35:20,285 (7f75595fa700) :  INFO (storeservice:356) - Starting automatic update check
2019-05-03 00:35:20,323 (7f75595fa700) :  DEBUG (runtime:1117) - Created a thread named 'remove_unavailable_agents'
2019-05-03 00:35:20,528 (7f75595fa700) :  DEBUG (networking:166) - Requesting 'https://plugins.plex.tv/apps/all.json?frameworkVersion=2.6.3&machineIdentifier=3e7b7fe94c75e0be03ba9545393f1604f763ce60&os=Linux&osVersion=4.9.0-8-amd64&cpu=i386&serverVersion=1.15.3.876-ad6e39743&systemRevision=ad6e397'
2019-05-03 00:35:21,060 (7f75595fa700) :  INFO (storeservice:495) - No beta plugins.
2019-05-03 00:35:21,092 (7f75595fa700) :  INFO (storeservice:531) - 'Services' plug-in [com.plexapp.system.services] is up to date (62fcf1f)
2019-05-03 00:35:21,092 (7f75595fa700) :  INFO (storeservice:362) - All plug-ins are up to date
2019-05-03 00:35:21,097 (7f75595fa700) :  DEBUG (runtime:1150) - Scheduled a timed thread named 'auto_update_thread'
2019-05-03 00:35:25,510 (7f75527fc700) :  INFO (datakit:131) - Saved the dictionary file
2019-05-03 06:21:41,101 (7f7553fff700) :  DEBUG (runtime:1156) - Starting timed thread named 'auto_update_thread'
2019-05-03 06:21:41,107 (7f7553fff700) :  INFO (storeservice:356) - Starting automatic update check
2019-05-03 06:21:41,111 (7f7553fff700) :  DEBUG (runtime:1117) - Created a thread named 'remove_unavailable_agents'
2019-05-03 06:21:41,124 (7f7553fff700) :  DEBUG (networking:166) - Requesting 'https://plugins.plex.tv/apps/all.json?frameworkVersion=2.6.3&machineIdentifier=3e7b7fe94c75e0be03ba9545393f1604f763ce60&os=Linux&osVersion=4.9.0-8-amd64&cpu=i386&serverVersion=1.15.3.876-ad6e39743&systemRevision=ad6e397'
2019-05-03 06:21:41,339 (7f7553fff700) :  INFO (storeservice:495) - No beta plugins.
2019-05-03 06:21:41,345 (7f7553fff700) :  INFO (storeservice:531) - 'Services' plug-in [com.plexapp.system.services] is up to date (62fcf1f)
2019-05-03 06:21:41,346 (7f7553fff700) :  INFO (storeservice:362) - All plug-ins are up to date
2019-05-03 06:21:41,346 (7f7553fff700) :  DEBUG (runtime:1150) - Scheduled a timed thread named 'auto_update_thread'
2019-05-03 06:21:46,137 (7f75595fa700) :  INFO (datakit:131) - Saved the dictionary file
2019-05-03 13:04:11,431 (7f75527fc700) :  DEBUG (runtime:1156) - Starting timed thread named 'auto_update_thread'
2019-05-03 13:04:11,487 (7f75527fc700) :  INFO (storeservice:356) - Starting automatic update check
2019-05-03 13:04:11,535 (7f75527fc700) :  DEBUG (runtime:1117) - Created a thread named 'remove_unavailable_agents'
2019-05-03 13:04:11,668 (7f75527fc700) :  DEBUG (networking:166) - Requesting 'https://plugins.plex.tv/apps/all.json?frameworkVersion=2.6.3&machineIdentifier=3e7b7fe94c75e0be03ba9545393f1604f763ce60&os=Linux&osVersion=4.9.0-8-amd64&cpu=i386&serverVersion=1.15.3.876-ad6e39743&systemRevision=ad6e397'
2019-05-03 13:04:12,571 (7f75527fc700) :  INFO (storeservice:495) - No beta plugins.
2019-05-03 13:04:12,579 (7f75527fc700) :  INFO (storeservice:531) - 'Services' plug-in [com.plexapp.system.services] is up to date (62fcf1f)
2019-05-03 13:04:12,579 (7f75527fc700) :  INFO (storeservice:362) - All plug-ins are up to date
2019-05-03 13:04:12,611 (7f75527fc700) :  DEBUG (runtime:1150) - Scheduled a timed thread named 'auto_update_thread'
2019-05-03 13:04:16,647 (7f7553fff700) :  INFO (datakit:131) - Saved the dictionary file
2019-05-03 17:50:10,615 (7f75595fa700) :  DEBUG (runtime:1156) - Starting timed thread named 'auto_update_thread'
2019-05-03 17:50:10,622 (7f75595fa700) :  INFO (storeservice:356) - Starting automatic update check
2019-05-03 17:50:10,627 (7f75595fa700) :  DEBUG (runtime:1117) - Created a thread named 'remove_unavailable_agents'
2019-05-03 17:50:10,640 (7f75595fa700) :  DEBUG (networking:166) - Requesting 'https://plugins.plex.tv/apps/all.json?frameworkVersion=2.6.3&machineIdentifier=3e7b7fe94c75e0be03ba9545393f1604f763ce60&os=Linux&osVersion=4.9.0-8-amd64&cpu=i386&serverVersion=1.15.3.876-ad6e39743&systemRevision=ad6e397'
2019-05-03 17:50:10,779 (7f75595fa700) :  INFO (storeservice:495) - No beta plugins.
2019-05-03 17:50:10,799 (7f75595fa700) :  INFO (storeservice:531) - 'Services' plug-in [com.plexapp.system.services] is up to date (62fcf1f)
2019-05-03 17:50:10,799 (7f75595fa700) :  INFO (storeservice:362) - All plug-ins are up to date
2019-05-03 17:50:10,800 (7f75595fa700) :  DEBUG (runtime:1150) - Scheduled a timed thread named 'auto_update_thread'
2019-05-03 17:50:15,653 (7f75527fc700) :  INFO (datakit:131) - Saved the dictionary file
2019-05-04 01:36:01,804 (7f7553fff700) :  DEBUG (runtime:1156) - Starting timed thread named 'auto_update_thread'
2019-05-04 01:36:01,810 (7f7553fff700) :  INFO (storeservice:356) - Starting automatic update check
2019-05-04 01:36:01,815 (7f7553fff700) :  DEBUG (runtime:1117) - Created a thread named 'remove_unavailable_agents'
2019-05-04 01:36:01,826 (7f7553fff700) :  DEBUG (networking:166) - Requesting 'https://plugins.plex.tv/apps/all.json?frameworkVersion=2.6.3&machineIdentifier=3e7b7fe94c75e0be03ba9545393f1604f763ce60&os=Linux&osVersion=4.9.0-8-amd64&cpu=i386&serverVersion=1.15.3.876-ad6e39743&systemRevision=ad6e397'
2019-05-04 01:36:01,959 (7f7553fff700) :  INFO (storeservice:495) - No beta plugins.
2019-05-04 01:36:01,965 (7f7553fff700) :  INFO (storeservice:531) - 'Services' plug-in [com.plexapp.system.services] is up to date (62fcf1f)
2019-05-04 01:36:01,966 (7f7553fff700) :  INFO (storeservice:362) - All plug-ins are up to date
2019-05-04 01:36:01,966 (7f7553fff700) :  DEBUG (runtime:1150) - Scheduled a timed thread named 'auto_update_thread'
2019-05-04 01:36:06,838 (7f75595fa700) :  INFO (datakit:131) - Saved the dictionary file
2019-05-04 07:04:19,967 (7f75527fc700) :  DEBUG (runtime:1156) - Starting timed thread named 'auto_update_thread'
2019-05-04 07:04:19,970 (7f75527fc700) :  INFO (storeservice:356) - Starting automatic update check
2019-05-04 07:04:19,971 (7f75527fc700) :  DEBUG (runtime:1117) - Created a thread named 'remove_unavailable_agents'
2019-05-04 07:04:19,974 (7f75527fc700) :  DEBUG (networking:166) - Requesting 'https://plugins.plex.tv/apps/all.json?frameworkVersion=2.6.3&machineIdentifier=3e7b7fe94c75e0be03ba9545393f1604f763ce60&os=Linux&osVersion=4.9.0-8-amd64&cpu=i386&serverVersion=1.15.3.876-ad6e39743&systemRevision=ad6e397'
2019-05-04 07:04:20,071 (7f75527fc700) :  INFO (storeservice:495) - No beta plugins.
2019-05-04 07:04:20,079 (7f75527fc700) :  INFO (storeservice:531) - 'Services' plug-in [com.plexapp.system.services] is up to date (62fcf1f)
2019-05-04 07:04:20,079 (7f75527fc700) :  INFO (storeservice:362) - All plug-ins are up to date
2019-05-04 07:04:20,080 (7f75527fc700) :  DEBUG (runtime:1150) - Scheduled a timed thread named 'auto_update_thread'
2019-05-04 07:04:24,985 (7f7553fff700) :  INFO (datakit:131) - Saved the dictionary file
2019-05-04 09:58:42,709 (7f7553fff700) :  DEBUG (runtime:717) - Handling request GET /system/messaging/clear_events/com.plexapp.agents.imdb
2019-05-04 09:58:42,751 (7f7553fff700) :  DEBUG (runtime:814) - Found route matching /system/messaging/clear_events/com.plexapp.agents.imdb
2019-05-04 09:58:42,753 (7f7553fff700) :  DEBUG (runtime:924) - Response: [200] str, 0 bytes
2019-05-04 09:58:42,755 (7f75527fc700) :  DEBUG (runtime:717) - Handling request GET /:/plugins/com.plexapp.system/resourceHashes
2019-05-04 09:58:42,757 (7f75527fc700) :  DEBUG (runtime:814) - Found route matching /:/plugins/com.plexapp.system/resourceHashes
2019-05-04 09:58:42,789 (7f75527fc700) :  DEBUG (networking:166) - Requesting 'http://resources-cdn.plexapp.com/hashes.json'
2019-05-04 09:58:52,842 (7f7553fff700) :  DEBUG (runtime:717) - Handling request GET /:/plugins/com.plexapp.system/messaging/function/X0J1bmRsZVNlcnZpY2U6QWxsU2VydmljZXM_/Y2VyZWFsMQoxCmxpc3QKMApyMAo_/Y2VyZWFsMQoxCmRpY3QKMApyMAo_
2019-05-04 09:58:52,929 (7f7553fff700) :  DEBUG (runtime:814) - Found route matching /:/plugins/com.plexapp.system/messaging/function/X0J1bmRsZVNlcnZpY2U6QWxsU2VydmljZXM_/Y2VyZWFsMQoxCmxpc3QKMApyMAo_/Y2VyZWFsMQoxCmRpY3QKMApyMAo_
2019-05-04 09:58:53,396 (7f7553fff700) :  DEBUG (runtime:924) - Response: [200] str, 59980 bytes
2019-05-04 09:58:53,663 (7f7553fff700) :  DEBUG (runtime:717) - Handling request GET /:/plugins/com.plexapp.system/messaging/function/X0FnZW50U2VydmljZTpVcGRhdGVJbmZv/Y2VyZWFsMQoxCmxpc3QKMApyMAo_/Y2VyZWFsMQo3CmRpY3QKbGlzdApkaWN0Cmxpc3QKbGlzdApsaXN0Cmxpc3QKMgpzMjMKY29tLnBsZXhhcHAuYWdlbnRzLmltZGJzMTAKaWRlbnRpZmllcnIxCnMxMAphZ2VudF9pbmZvMQpyMgoxMApyMwpzMTEKbWVkaWFfdHlwZXNyNApzMTIKYWNjZXB0c19mcm9tbnMxNApmYWxsYmFja19hZ2VudHI1CnMxNApjb250cmlidXRlc190b3I2CnM5Cmxhbmd1YWdlc2IxczIwCnBlcnNpc3Rfc3RvcmVkX2ZpbGVzaTAKczcKdmVyc2lvbmIxczE2CnByaW1hcnlfcHJvdmlkZXJiMXM1CnByZWZzczEwClBsZXggTW92aWVzNApuYW1lMQpzNQpNb3ZpZTEKczI5CmNvbS5wbGV4YXBwLmFnZW50cy5sb2NhbG1lZGlhMQpzMjkKY29tLnBsZXhhcHAuYWdlbnRzLnRoZW1vdmllZGIzMwpzMgplbnMyCnN2czIKZnJzMgplc3MyCm5sczIKZGVzMgppdHMyCmRhczIKYXJzMgpjYXMyCnpoczIKY3NzMgpldHMyCmZpczIKZWxzMgpoZXMyCmhpczIKaHVzMgppZHMyCmphczIKa29zMgpsdnMyCm5vczIKZmFzMgpwbHMyCnB0czIKcm9zMgpydXMyCnNrczIKdGhzMgp0cnMyCnVrczIKdmlyMAo_
2019-05-04 09:58:53,664 (7f7553fff700) :  DEBUG (runtime:814) - Found route matching /:/plugins/com.plexapp.system/messaging/function/X0FnZW50U2VydmljZTpVcGRhdGVJbmZv/Y2VyZWFsMQoxCmxpc3QKMApyMAo_/Y2VyZWFsMQo3CmRpY3QKbGlzdApkaWN0Cmxpc3QKbGlzdApsaXN0Cmxpc3QKMgpzMjMKY29tLnBsZXhhcHAuYWdlbnRzLmltZGJzMTAKaWRlbnRpZmllcnIxCnMxMAphZ2VudF9pbmZvMQpyMgoxMApyMwpzMTEKbWVkaWFfdHlwZXNyNApzMTIKYWNjZXB0c19mcm9tbnMxNApmYWxsYmFja19hZ2VudHI1CnMxNApjb250cmlidXRlc190b3I2CnM5Cmxhbmd1YWdlc2IxczIwCnBlcnNpc3Rfc3RvcmVkX2ZpbGVzaTAKczcKdmVyc2lvbmIxczE2CnByaW1hcnlfcHJvdmlkZXJiMXM1CnByZWZzczEwClBsZXggTW92aWVzNApuYW1lMQpzNQpNb3ZpZTEKczI5CmNvbS5wbGV4YXBwLmFnZW50cy5sb2NhbG1lZGlhMQpzMjkKY29tLnBsZXhhcHAuYWdlbnRzLnRoZW1vdmllZGIzMwpzMgplbnMyCnN2czIKZnJzMgplc3MyCm5sczIKZGVzMgppdHMyCmRhczIKYXJzMgpjYXMyCnpoczIKY3NzMgpldHMyCmZpczIKZWxzMgpoZXMyCmhpczIKaHVzMgppZHMyCmphczIKa29zMgpsdnMyCm5vczIKZmFzMgpwbHMyCnB0czIKcm9zMgpydXMyCnNrczIKdGhzMgp0cnMyCnVrczIKdmlyMAo_
2019-05-04 09:58:53,666 (7f7553fff700) :  INFO (agentservice:167) - Receiving agent info from com.plexapp.agents.imdb: [{'media_types': ['Movie'], 'primary_provider': True, 'fallback_agent': None, 'contributes_to': ['com.plexapp.agents.themoviedb'], 'languages': ['en', 'sv', 'fr', 'es', 'nl', 'de', 'it', 'da', 'ar', 'ca', 'zh', 'cs', 'et', 'fi', 'el', 'he', 'hi', 'hu', 'id', 'ja', 'ko', 'lv', 'no', 'fa', 'pl', 'pt', 'ro', 'ru', 'sk', 'th', 'tr', 'uk', 'vi'], 'persist_stored_files': True, 'version': 0, 'accepts_from': ['com.plexapp.agents.localmedia'], 'prefs': True, 'name': 'Plex Movie'}]
2019-05-04 09:58:53,670 (7f7553fff700) :  DEBUG (runtime:924) - Response: [200] str, 16 bytes
2019-05-04 09:58:58,722 (7f75537fe700) :  INFO (datakit:131) - Saved the dictionary file
2019-05-04 09:59:02,896 (7f75527fc700) :  CRITICAL (runtime:1299) - Exception getting hosted resource hashes (most recent call last):
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-ad6e39743/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/components/runtime.py", line 1291, in get_resource_hashes
    json = self._core.networking.http_request("http://resources-cdn.plexapp.com/hashes.json", timeout=5).content
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-ad6e39743/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/components/networking.py", line 265, in content
    return self.__str__()
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-ad6e39743/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/components/networking.py", line 243, in __str__
    self.load()
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-ad6e39743/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/components/networking.py", line 181, in load
    f = self._opener.open(req, timeout=self._timeout)
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-ad6e39743/Framework.bundle/Contents/Resources/Platforms/Shared/Libraries/urllib2_new.py", line 438, in open
    response = self._open(req, data)
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-ad6e39743/Framework.bundle/Contents/Resources/Platforms/Shared/Libraries/urllib2_new.py", line 456, in _open
    '_open', req)
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-ad6e39743/Framework.bundle/Contents/Resources/Platforms/Shared/Libraries/urllib2_new.py", line 416, in _call_chain
    result = func(*args)
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-ad6e39743/Framework.bundle/Contents/Resources/Platforms/Shared/Libraries/urllib2_new.py", line 1217, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-ad6e39743/Framework.bundle/Contents/Resources/Platforms/Shared/Libraries/urllib2_new.py", line 1192, in do_open
    raise URLError(err)
URLError: <urlopen error [Errno -3] Temporary failure in name resolution>

2019-05-04 09:59:02,898 (7f75527fc700) :  DEBUG (runtime:924) - Response: [200] str, 13276 bytes
2019-05-04 14:24:56,083 (7f75595fa700) :  DEBUG (runtime:1156) - Starting timed thread named 'auto_update_thread'
2019-05-04 14:24:56,090 (7f75595fa700) :  INFO (storeservice:356) - Starting automatic update check
2019-05-04 14:24:56,120 (7f75595fa700) :  DEBUG (runtime:1117) - Created a thread named 'remove_unavailable_agents'
2019-05-04 14:24:56,164 (7f75595fa700) :  DEBUG (networking:166) - Requesting 'https://plugins.plex.tv/apps/all.json?frameworkVersion=2.6.3&machineIdentifier=3e7b7fe94c75e0be03ba9545393f1604f763ce60&os=Linux&osVersion=4.9.0-8-amd64&cpu=i386&serverVersion=1.15.3.876-ad6e39743&systemRevision=ad6e397'
2019-05-04 14:25:01,144 (7f75537fe700) :  INFO (datakit:131) - Saved the dictionary file
2019-05-04 14:25:16,191 (7f75595fa700) :  INFO (storeservice:509) - Failed to fetch Plex Online data - the store probably won't work
2019-05-04 14:25:16,226 (7f75595fa700) :  CRITICAL (storeservice:510) - Error info (most recent call last):
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-ad6e39743/System.bundle/Contents/Code/storeservice.py", line 495, in update
    log_msg = "Updated information for plug-in '%s' (class: %s) to a stable version"
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-ad6e39743/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/api/parsekit.py", line 145, in ObjectFromURL
    method=method,
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-ad6e39743/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/api/networkkit.py", line 67, in _http_request
    req = self._core.networking.http_request(url, *args, **kwargs)
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-ad6e39743/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/components/networking.py", line 370, in http_request
    return HTTPRequest(self._core, url, data, h, url_cache, encoding, errors, timeout, immediate, sleep, opener, follow_redirects, method)
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-ad6e39743/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/components/networking.py", line 141, in __init__
    self.load()
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-ad6e39743/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/components/networking.py", line 181, in load
    f = self._opener.open(req, timeout=self._timeout)
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-ad6e39743/Framework.bundle/Contents/Resources/Platforms/Shared/Libraries/urllib2_new.py", line 438, in open
    response = self._open(req, data)
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-ad6e39743/Framework.bundle/Contents/Resources/Platforms/Shared/Libraries/urllib2_new.py", line 456, in _open
    '_open', req)
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-ad6e39743/Framework.bundle/Contents/Resources/Platforms/Shared/Libraries/urllib2_new.py", line 416, in _call_chain
    result = func(*args)
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-ad6e39743/Framework.bundle/Contents/Resources/Platforms/Shared/Libraries/urllib2_new.py", line 1225, in https_open
    return self.do_open(httplib.HTTPSConnection, req)
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-ad6e39743/Framework.bundle/Contents/Resources/Platforms/Shared/Libraries/urllib2_new.py", line 1192, in do_open
    raise URLError(err)
URLError: <urlopen error [Errno -3] Temporary failure in name resolution>

2019-05-04 14:25:16,229 (7f75595fa700) :  INFO (storeservice:531) - 'Services' plug-in [com.plexapp.system.services] is up to date (62fcf1f)
2019-05-04 14:25:16,230 (7f75595fa700) :  INFO (storeservice:362) - All plug-ins are up to date
2019-05-04 14:25:16,231 (7f75595fa700) :  DEBUG (runtime:1150) - Scheduled a timed thread named 'auto_update_thread'
2019-05-04 21:54:22,234 (7f75537fe700) :  DEBUG (runtime:1156) - Starting timed thread named 'auto_update_thread'
2019-05-04 21:54:22,241 (7f75537fe700) :  INFO (storeservice:356) - Starting automatic update check
2019-05-04 21:54:22,245 (7f75537fe700) :  DEBUG (runtime:1117) - Created a thread named 'remove_unavailable_agents'
2019-05-04 21:54:22,257 (7f75537fe700) :  DEBUG (networking:166) - Requesting 'https://plugins.plex.tv/apps/all.json?frameworkVersion=2.6.3&machineIdentifier=3e7b7fe94c75e0be03ba9545393f1604f763ce60&os=Linux&osVersion=4.9.0-8-amd64&cpu=i386&serverVersion=1.15.3.876-ad6e39743&systemRevision=ad6e397'
2019-05-04 21:54:27,273 (7f75527fc700) :  INFO (datakit:131) - Saved the dictionary file
2019-05-04 21:54:42,285 (7f75537fe700) :  INFO (storeservice:509) - Failed to fetch Plex Online data - the store probably won't work
2019-05-04 21:54:42,287 (7f75537fe700) :  CRITICAL (storeservice:510) - Error info (most recent call last):
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-ad6e39743/System.bundle/Contents/Code/storeservice.py", line 495, in update
    log_msg = "Updated information for plug-in '%s' (class: %s) to a stable version"
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-ad6e39743/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/api/parsekit.py", line 145, in ObjectFromURL
    method=method,
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-ad6e39743/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/api/networkkit.py", line 67, in _http_request
    req = self._core.networking.http_request(url, *args, **kwargs)
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-ad6e39743/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/components/networking.py", line 370, in http_request
    return HTTPRequest(self._core, url, data, h, url_cache, encoding, errors, timeout, immediate, sleep, opener, follow_redirects, method)
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-ad6e39743/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/components/networking.py", line 141, in __init__
    self.load()
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-ad6e39743/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/components/networking.py", line 181, in load
    f = self._opener.open(req, timeout=self._timeout)
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-ad6e39743/Framework.bundle/Contents/Resources/Platforms/Shared/Libraries/urllib2_new.py", line 438, in open
    response = self._open(req, data)
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-ad6e39743/Framework.bundle/Contents/Resources/Platforms/Shared/Libraries/urllib2_new.py", line 456, in _open
    '_open', req)
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-ad6e39743/Framework.bundle/Contents/Resources/Platforms/Shared/Libraries/urllib2_new.py", line 416, in _call_chain
    result = func(*args)
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-ad6e39743/Framework.bundle/Contents/Resources/Platforms/Shared/Libraries/urllib2_new.py", line 1225, in https_open
    return self.do_open(httplib.HTTPSConnection, req)
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-ad6e39743/Framework.bundle/Contents/Resources/Platforms/Shared/Libraries/urllib2_new.py", line 1192, in do_open
    raise URLError(err)
URLError: <urlopen error [Errno -3] Temporary failure in name resolution>

2019-05-04 21:54:42,290 (7f75537fe700) :  INFO (storeservice:531) - 'Services' plug-in [com.plexapp.system.services] is up to date (62fcf1f)
2019-05-04 21:54:42,290 (7f75537fe700) :  INFO (storeservice:362) - All plug-ins are up to date
2019-05-04 21:54:42,292 (7f75537fe700) :  DEBUG (runtime:1150) - Scheduled a timed thread named 'auto_update_thread'
2019-05-05 03:46:34,295 (7f75527fc700) :  DEBUG (runtime:1156) - Starting timed thread named 'auto_update_thread'
2019-05-05 03:46:34,301 (7f75527fc700) :  INFO (storeservice:356) - Starting automatic update check
2019-05-05 03:46:34,305 (7f75527fc700) :  DEBUG (runtime:1117) - Created a thread named 'remove_unavailable_agents'
2019-05-05 03:46:34,324 (7f75527fc700) :  DEBUG (networking:166) - Requesting 'https://plugins.plex.tv/apps/all.json?frameworkVersion=2.6.3&machineIdentifier=3e7b7fe94c75e0be03ba9545393f1604f763ce60&os=Linux&osVersion=4.9.0-8-amd64&cpu=i386&serverVersion=1.15.3.876-ad6e39743&systemRevision=ad6e397'
2019-05-05 03:46:39,342 (7f75595fa700) :  INFO (datakit:131) - Saved the dictionary file
2019-05-05 03:46:54,352 (7f75527fc700) :  INFO (storeservice:509) - Failed to fetch Plex Online data - the store probably won't work
2019-05-05 03:46:54,354 (7f75527fc700) :  CRITICAL (storeservice:510) - Error info (most recent call last):
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-ad6e39743/System.bundle/Contents/Code/storeservice.py", line 495, in update
    log_msg = "Updated information for plug-in '%s' (class: %s) to a stable version"
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-ad6e39743/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/api/parsekit.py", line 145, in ObjectFromURL
    method=method,
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-ad6e39743/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/api/networkkit.py", line 67, in _http_request
    req = self._core.networking.http_request(url, *args, **kwargs)
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-ad6e39743/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/components/networking.py", line 370, in http_request
    return HTTPRequest(self._core, url, data, h, url_cache, encoding, errors, timeout, immediate, sleep, opener, follow_redirects, method)
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-ad6e39743/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/components/networking.py", line 141, in __init__
    self.load()
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-ad6e39743/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/components/networking.py", line 181, in load
    f = self._opener.open(req, timeout=self._timeout)
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-ad6e39743/Framework.bundle/Contents/Resources/Platforms/Shared/Libraries/urllib2_new.py", line 438, in open
    response = self._open(req, data)
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-ad6e39743/Framework.bundle/Contents/Resources/Platforms/Shared/Libraries/urllib2_new.py", line 456, in _open
    '_open', req)
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-ad6e39743/Framework.bundle/Contents/Resources/Platforms/Shared/Libraries/urllib2_new.py", line 416, in _call_chain
    result = func(*args)
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-ad6e39743/Framework.bundle/Contents/Resources/Platforms/Shared/Libraries/urllib2_new.py", line 1225, in https_open
    return self.do_open(httplib.HTTPSConnection, req)
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-ad6e39743/Framework.bundle/Contents/Resources/Platforms/Shared/Libraries/urllib2_new.py", line 1192, in do_open
    raise URLError(err)
URLError: <urlopen error [Errno -3] Temporary failure in name resolution>

2019-05-05 03:46:54,355 (7f75527fc700) :  INFO (storeservice:531) - 'Services' plug-in [com.plexapp.system.services] is up to date (62fcf1f)
2019-05-05 03:46:54,355 (7f75527fc700) :  INFO (storeservice:362) - All plug-ins are up to date
2019-05-05 03:46:54,356 (7f75527fc700) :  DEBUG (runtime:1150) - Scheduled a timed thread named 'auto_update_thread'
2019-05-05 11:42:32,359 (7f75595fa700) :  DEBUG (runtime:1156) - Starting timed thread named 'auto_update_thread'
2019-05-05 11:42:32,366 (7f75595fa700) :  INFO (storeservice:356) - Starting automatic update check
2019-05-05 11:42:32,370 (7f75595fa700) :  DEBUG (runtime:1117) - Created a thread named 'remove_unavailable_agents'
2019-05-05 11:42:32,382 (7f75595fa700) :  DEBUG (networking:166) - Requesting 'https://plugins.plex.tv/apps/all.json?frameworkVersion=2.6.3&machineIdentifier=3e7b7fe94c75e0be03ba9545393f1604f763ce60&os=Linux&osVersion=4.9.0-8-amd64&cpu=i386&serverVersion=1.15.3.876-ad6e39743&systemRevision=ad6e397'
2019-05-05 11:42:37,397 (7f75537fe700) :  INFO (datakit:131) - Saved the dictionary file
2019-05-05 11:42:52,412 (7f75595fa700) :  INFO (storeservice:509) - Failed to fetch Plex Online data - the store probably won't work
2019-05-05 11:42:52,414 (7f75595fa700) :  CRITICAL (storeservice:510) - Error info (most recent call last):
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-ad6e39743/System.bundle/Contents/Code/storeservice.py", line 495, in update
    log_msg = "Updated information for plug-in '%s' (class: %s) to a stable version"
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-ad6e39743/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/api/parsekit.py", line 145, in ObjectFromURL
    method=method,
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-ad6e39743/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/api/networkkit.py", line 67, in _http_request
    req = self._core.networking.http_request(url, *args, **kwargs)
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-ad6e39743/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/components/networking.py", line 370, in http_request
    return HTTPRequest(self._core, url, data, h, url_cache, encoding, errors, timeout, immediate, sleep, opener, follow_redirects, method)
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-ad6e39743/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/components/networking.py", line 141, in __init__
    self.load()
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-ad6e39743/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/components/networking.py", line 181, in load
    f = self._opener.open(req, timeout=self._timeout)
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-ad6e39743/Framework.bundle/Contents/Resources/Platforms/Shared/Libraries/urllib2_new.py", line 438, in open
    response = self._open(req, data)
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-ad6e39743/Framework.bundle/Contents/Resources/Platforms/Shared/Libraries/urllib2_new.py", line 456, in _open
    '_open', req)
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-ad6e39743/Framework.bundle/Contents/Resources/Platforms/Shared/Libraries/urllib2_new.py", line 416, in _call_chain
    result = func(*args)
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-ad6e39743/Framework.bundle/Contents/Resources/Platforms/Shared/Libraries/urllib2_new.py", line 1225, in https_open
    return self.do_open(httplib.HTTPSConnection, req)
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-ad6e39743/Framework.bundle/Contents/Resources/Platforms/Shared/Libraries/urllib2_new.py", line 1192, in do_open
    raise URLError(err)
URLError: <urlopen error [Errno -3] Temporary failure in name resolution>

2019-05-05 11:42:52,417 (7f75595fa700) :  INFO (storeservice:531) - 'Services' plug-in [com.plexapp.system.services] is up to date (62fcf1f)
2019-05-05 11:42:52,417 (7f75595fa700) :  INFO (storeservice:362) - All plug-ins are up to date
2019-05-05 11:42:52,418 (7f75595fa700) :  DEBUG (runtime:1150) - Scheduled a timed thread named 'auto_update_thread'
2019-05-05 17:28:13,422 (7f75537fe700) :  DEBUG (runtime:1156) - Starting timed thread named 'auto_update_thread'
2019-05-05 17:28:13,429 (7f75537fe700) :  INFO (storeservice:356) - Starting automatic update check
2019-05-05 17:28:13,433 (7f75537fe700) :  DEBUG (runtime:1117) - Created a thread named 'remove_unavailable_agents'
2019-05-05 17:28:13,446 (7f75537fe700) :  DEBUG (networking:166) - Requesting 'https://plugins.plex.tv/apps/all.json?frameworkVersion=2.6.3&machineIdentifier=3e7b7fe94c75e0be03ba9545393f1604f763ce60&os=Linux&osVersion=4.9.0-8-amd64&cpu=i386&serverVersion=1.15.3.876-ad6e39743&systemRevision=ad6e397'
2019-05-05 17:28:18,463 (7f75527fc700) :  INFO (datakit:131) - Saved the dictionary file
2019-05-05 17:28:33,473 (7f75537fe700) :  INFO (storeservice:509) - Failed to fetch Plex Online data - the store probably won't work
2019-05-05 17:28:33,475 (7f75537fe700) :  CRITICAL (storeservice:510) - Error info (most recent call last):
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-ad6e39743/System.bundle/Contents/Code/storeservice.py", line 495, in update
    log_msg = "Updated information for plug-in '%s' (class: %s) to a stable version"
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-ad6e39743/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/api/parsekit.py", line 145, in ObjectFromURL
    method=method,
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-ad6e39743/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/api/networkkit.py", line 67, in _http_request
    req = self._core.networking.http_request(url, *args, **kwargs)
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-ad6e39743/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/components/networking.py", line 370, in http_request
    return HTTPRequest(self._core, url, data, h, url_cache, encoding, errors, timeout, immediate, sleep, opener, follow_redirects, method)
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-ad6e39743/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/components/networking.py", line 141, in __init__
    self.load()
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-ad6e39743/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/components/networking.py", line 181, in load
    f = self._opener.open(req, timeout=self._timeout)
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-ad6e39743/Framework.bundle/Contents/Resources/Platforms/Shared/Libraries/urllib2_new.py", line 438, in open
    response = self._open(req, data)
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-ad6e39743/Framework.bundle/Contents/Resources/Platforms/Shared/Libraries/urllib2_new.py", line 456, in _open
    '_open', req)
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-ad6e39743/Framework.bundle/Contents/Resources/Platforms/Shared/Libraries/urllib2_new.py", line 416, in _call_chain
    result = func(*args)
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-ad6e39743/Framework.bundle/Contents/Resources/Platforms/Shared/Libraries/urllib2_new.py", line 1225, in https_open
    return self.do_open(httplib.HTTPSConnection, req)
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-ad6e39743/Framework.bundle/Contents/Resources/Platforms/Shared/Libraries/urllib2_new.py", line 1192, in do_open
    raise URLError(err)
URLError: <urlopen error [Errno -3] Temporary failure in name resolution>

2019-05-05 17:28:33,477 (7f75537fe700) :  INFO (storeservice:531) - 'Services' plug-in [com.plexapp.system.services] is up to date (62fcf1f)
2019-05-05 17:28:33,478 (7f75537fe700) :  INFO (storeservice:362) - All plug-ins are up to date
2019-05-05 17:28:33,479 (7f75537fe700) :  DEBUG (runtime:1150) - Scheduled a timed thread named 'auto_update_thread'
2019-05-06 00:31:52,482 (7f75527fc700) :  DEBUG (runtime:1156) - Starting timed thread named 'auto_update_thread'
2019-05-06 00:31:52,489 (7f75527fc700) :  INFO (storeservice:356) - Starting automatic update check
2019-05-06 00:31:52,493 (7f75527fc700) :  DEBUG (runtime:1117) - Created a thread named 'remove_unavailable_agents'
2019-05-06 00:31:52,505 (7f75527fc700) :  DEBUG (networking:166) - Requesting 'https://plugins.plex.tv/apps/all.json?frameworkVersion=2.6.3&machineIdentifier=3e7b7fe94c75e0be03ba9545393f1604f763ce60&os=Linux&osVersion=4.9.0-8-amd64&cpu=i386&serverVersion=1.15.3.876-ad6e39743&systemRevision=ad6e397'
2019-05-06 00:31:57,526 (7f75595fa700) :  INFO (datakit:131) - Saved the dictionary file
2019-05-06 00:32:12,533 (7f75527fc700) :  INFO (storeservice:509) - Failed to fetch Plex Online data - the store probably won't work
2019-05-06 00:32:12,536 (7f75527fc700) :  CRITICAL (storeservice:510) - Error info (most recent call last):
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-ad6e39743/System.bundle/Contents/Code/storeservice.py", line 495, in update
    log_msg = "Updated information for plug-in '%s' (class: %s) to a stable version"
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-ad6e39743/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/api/parsekit.py", line 145, in ObjectFromURL
    method=method,
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-ad6e39743/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/api/networkkit.py", line 67, in _http_request
    req = self._core.networking.http_request(url, *args, **kwargs)
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-ad6e39743/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/components/networking.py", line 370, in http_request
    return HTTPRequest(self._core, url, data, h, url_cache, encoding, errors, timeout, immediate, sleep, opener, follow_redirects, method)
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-ad6e39743/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/components/networking.py", line 141, in __init__
    self.load()
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-ad6e39743/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/components/networking.py", line 181, in load
    f = self._opener.open(req, timeout=self._timeout)
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-ad6e39743/Framework.bundle/Contents/Resources/Platforms/Shared/Libraries/urllib2_new.py", line 438, in open
    response = self._open(req, data)
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-ad6e39743/Framework.bundle/Contents/Resources/Platforms/Shared/Libraries/urllib2_new.py", line 456, in _open
    '_open', req)
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-ad6e39743/Framework.bundle/Contents/Resources/Platforms/Shared/Libraries/urllib2_new.py", line 416, in _call_chain
    result = func(*args)
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-ad6e39743/Framework.bundle/Contents/Resources/Platforms/Shared/Libraries/urllib2_new.py", line 1225, in https_open
    return self.do_open(httplib.HTTPSConnection, req)
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-ad6e39743/Framework.bundle/Contents/Resources/Platforms/Shared/Libraries/urllib2_new.py", line 1192, in do_open
    raise URLError(err)
URLError: <urlopen error [Errno -3] Temporary failure in name resolution>

2019-05-06 00:32:12,539 (7f75527fc700) :  INFO (storeservice:531) - 'Services' plug-in [com.plexapp.system.services] is up to date (62fcf1f)
2019-05-06 00:32:12,539 (7f75527fc700) :  INFO (storeservice:362) - All plug-ins are up to date
2019-05-06 00:32:12,540 (7f75527fc700) :  DEBUG (runtime:1150) - Scheduled a timed thread named 'auto_update_thread'
2019-05-06 04:48:08,544 (7f75595fa700) :  DEBUG (runtime:1156) - Starting timed thread named 'auto_update_thread'
2019-05-06 04:48:08,551 (7f75595fa700) :  INFO (storeservice:356) - Starting automatic update check
2019-05-06 04:48:08,555 (7f75595fa700) :  DEBUG (runtime:1117) - Created a thread named 'remove_unavailable_agents'
2019-05-06 04:48:08,568 (7f75595fa700) :  DEBUG (networking:166) - Requesting 'https://plugins.plex.tv/apps/all.json?frameworkVersion=2.6.3&machineIdentifier=3e7b7fe94c75e0be03ba9545393f1604f763ce60&os=Linux&osVersion=4.9.0-8-amd64&cpu=i386&serverVersion=1.15.3.876-ad6e39743&systemRevision=ad6e397'
2019-05-06 04:48:13,589 (7f75537fe700) :  INFO (datakit:131) - Saved the dictionary file
2019-05-06 04:48:28,599 (7f75595fa700) :  INFO (storeservice:509) - Failed to fetch Plex Online data - the store probably won't work
2019-05-06 04:48:28,601 (7f75595fa700) :  CRITICAL (storeservice:510) - Error info (most recent call last):
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-ad6e39743/System.bundle/Contents/Code/storeservice.py", line 495, in update
    log_msg = "Updated information for plug-in '%s' (class: %s) to a stable version"
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-ad6e39743/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/api/parsekit.py", line 145, in ObjectFromURL
    method=method,
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-ad6e39743/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/api/networkkit.py", line 67, in _http_request
    req = self._core.networking.http_request(url, *args, **kwargs)
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-ad6e39743/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/components/networking.py", line 370, in http_request
    return HTTPRequest(self._core, url, data, h, url_cache, encoding, errors, timeout, immediate, sleep, opener, follow_redirects, method)
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-ad6e39743/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/components/networking.py", line 141, in __init__
    self.load()
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-ad6e39743/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/components/networking.py", line 181, in load
    f = self._opener.open(req, timeout=self._timeout)
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-ad6e39743/Framework.bundle/Contents/Resources/Platforms/Shared/Libraries/urllib2_new.py", line 438, in open
    response = self._open(req, data)
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-ad6e39743/Framework.bundle/Contents/Resources/Platforms/Shared/Libraries/urllib2_new.py", line 456, in _open
    '_open', req)
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-ad6e39743/Framework.bundle/Contents/Resources/Platforms/Shared/Libraries/urllib2_new.py", line 416, in _call_chain
    result = func(*args)
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-ad6e39743/Framework.bundle/Contents/Resources/Platforms/Shared/Libraries/urllib2_new.py", line 1225, in https_open
    return self.do_open(httplib.HTTPSConnection, req)
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-ad6e39743/Framework.bundle/Contents/Resources/Platforms/Shared/Libraries/urllib2_new.py", line 1192, in do_open
    raise URLError(err)
URLError: <urlopen error [Errno -3] Temporary failure in name resolution>

2019-05-06 04:48:28,603 (7f75595fa700) :  INFO (storeservice:531) - 'Services' plug-in [com.plexapp.system.services] is up to date (62fcf1f)
2019-05-06 04:48:28,604 (7f75595fa700) :  INFO (storeservice:362) - All plug-ins are up to date
2019-05-06 04:48:28,605 (7f75595fa700) :  DEBUG (runtime:1150) - Scheduled a timed thread named 'auto_update_thread'
2019-05-06 09:59:13,608 (7f75537fe700) :  DEBUG (runtime:1156) - Starting timed thread named 'auto_update_thread'
2019-05-06 09:59:13,615 (7f75537fe700) :  INFO (storeservice:356) - Starting automatic update check
2019-05-06 09:59:13,619 (7f75537fe700) :  DEBUG (runtime:1117) - Created a thread named 'remove_unavailable_agents'
2019-05-06 09:59:13,631 (7f75537fe700) :  DEBUG (networking:166) - Requesting 'https://plugins.plex.tv/apps/all.json?frameworkVersion=2.6.3&machineIdentifier=3e7b7fe94c75e0be03ba9545393f1604f763ce60&os=Linux&osVersion=4.9.0-8-amd64&cpu=i386&serverVersion=1.15.3.876-ad6e39743&systemRevision=ad6e397'
2019-05-06 09:59:18,652 (7f75527fc700) :  INFO (datakit:131) - Saved the dictionary file
2019-05-06 09:59:26,137 (7f75527fc700) :  DEBUG (runtime:717) - Handling request GET /system/messaging/clear_events/com.plexapp.agents.imdb
2019-05-06 09:59:26,141 (7f75527fc700) :  DEBUG (runtime:814) - Found route matching /system/messaging/clear_events/com.plexapp.agents.imdb
2019-05-06 09:59:26,164 (7f75527fc700) :  DEBUG (runtime:924) - Response: [200] str, 0 bytes
2019-05-06 09:59:26,168 (7f75527fc700) :  DEBUG (runtime:717) - Handling request GET /:/plugins/com.plexapp.system/resourceHashes
2019-05-06 09:59:26,170 (7f75527fc700) :  DEBUG (runtime:814) - Found route matching /:/plugins/com.plexapp.system/resourceHashes
2019-05-06 09:59:26,171 (7f75527fc700) :  DEBUG (networking:166) - Requesting 'http://resources-cdn.plexapp.com/hashes.json'
2019-05-06 09:59:33,662 (7f75537fe700) :  INFO (storeservice:509) - Failed to fetch Plex Online data - the store probably won't work
2019-05-06 09:59:33,664 (7f75537fe700) :  CRITICAL (storeservice:510) - Error info (most recent call last):
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-ad6e39743/System.bundle/Contents/Code/storeservice.py", line 495, in update
    log_msg = "Updated information for plug-in '%s' (class: %s) to a stable version"
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-ad6e39743/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/api/parsekit.py", line 145, in ObjectFromURL
    method=method,
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-ad6e39743/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/api/networkkit.py", line 67, in _http_request
    req = self._core.networking.http_request(url, *args, **kwargs)
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-ad6e39743/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/components/networking.py", line 370, in http_request
    return HTTPRequest(self._core, url, data, h, url_cache, encoding, errors, timeout, immediate, sleep, opener, follow_redirects, method)
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-ad6e39743/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/components/networking.py", line 141, in __init__
    self.load()
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-ad6e39743/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/components/networking.py", line 181, in load
    f = self._opener.open(req, timeout=self._timeout)
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-ad6e39743/Framework.bundle/Contents/Resources/Platforms/Shared/Libraries/urllib2_new.py", line 438, in open
    response = self._open(req, data)
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-ad6e39743/Framework.bundle/Contents/Resources/Platforms/Shared/Libraries/urllib2_new.py", line 456, in _open
    '_open', req)
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-ad6e39743/Framework.bundle/Contents/Resources/Platforms/Shared/Libraries/urllib2_new.py", line 416, in _call_chain
    result = func(*args)
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-ad6e39743/Framework.bundle/Contents/Resources/Platforms/Shared/Libraries/urllib2_new.py", line 1225, in https_open
    return self.do_open(httplib.HTTPSConnection, req)
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-ad6e39743/Framework.bundle/Contents/Resources/Platforms/Shared/Libraries/urllib2_new.py", line 1192, in do_open
    raise URLError(err)
URLError: <urlopen error [Errno -3] Temporary failure in name resolution>

2019-05-06 09:59:33,667 (7f75537fe700) :  INFO (storeservice:531) - 'Services' plug-in [com.plexapp.system.services] is up to date (62fcf1f)
2019-05-06 09:59:33,667 (7f75537fe700) :  INFO (storeservice:362) - All plug-ins are up to date
2019-05-06 09:59:33,668 (7f75537fe700) :  DEBUG (runtime:1150) - Scheduled a timed thread named 'auto_update_thread'
2019-05-06 09:59:36,269 (7f75537fe700) :  DEBUG (runtime:717) - Handling request GET /:/plugins/com.plexapp.system/messaging/function/X0J1bmRsZVNlcnZpY2U6QWxsU2VydmljZXM_/Y2VyZWFsMQoxCmxpc3QKMApyMAo_/Y2VyZWFsMQoxCmRpY3QKMApyMAo_
2019-05-06 09:59:36,271 (7f75537fe700) :  DEBUG (runtime:814) - Found route matching /:/plugins/com.plexapp.system/messaging/function/X0J1bmRsZVNlcnZpY2U6QWxsU2VydmljZXM_/Y2VyZWFsMQoxCmxpc3QKMApyMAo_/Y2VyZWFsMQoxCmRpY3QKMApyMAo_
2019-05-06 09:59:36,728 (7f75537fe700) :  DEBUG (runtime:924) - Response: [200] str, 59980 bytes
2019-05-06 09:59:36,973 (7f75537fe700) :  DEBUG (runtime:717) - Handling request GET /:/plugins/com.plexapp.system/messaging/function/X0FnZW50U2VydmljZTpVcGRhdGVJbmZv/Y2VyZWFsMQoxCmxpc3QKMApyMAo_/Y2VyZWFsMQo3CmRpY3QKbGlzdApkaWN0Cmxpc3QKbGlzdApsaXN0Cmxpc3QKMgpzMjMKY29tLnBsZXhhcHAuYWdlbnRzLmltZGJzMTAKaWRlbnRpZmllcnIxCnMxMAphZ2VudF9pbmZvMQpyMgoxMApyMwpzMTEKbWVkaWFfdHlwZXNyNApzMTIKYWNjZXB0c19mcm9tbnMxNApmYWxsYmFja19hZ2VudHI1CnMxNApjb250cmlidXRlc190b3I2CnM5Cmxhbmd1YWdlc2IxczIwCnBlcnNpc3Rfc3RvcmVkX2ZpbGVzaTAKczcKdmVyc2lvbmIxczE2CnByaW1hcnlfcHJvdmlkZXJiMXM1CnByZWZzczEwClBsZXggTW92aWVzNApuYW1lMQpzNQpNb3ZpZTEKczI5CmNvbS5wbGV4YXBwLmFnZW50cy5sb2NhbG1lZGlhMQpzMjkKY29tLnBsZXhhcHAuYWdlbnRzLnRoZW1vdmllZGIzMwpzMgplbnMyCnN2czIKZnJzMgplc3MyCm5sczIKZGVzMgppdHMyCmRhczIKYXJzMgpjYXMyCnpoczIKY3NzMgpldHMyCmZpczIKZWxzMgpoZXMyCmhpczIKaHVzMgppZHMyCmphczIKa29zMgpsdnMyCm5vczIKZmFzMgpwbHMyCnB0czIKcm9zMgpydXMyCnNrczIKdGhzMgp0cnMyCnVrczIKdmlyMAo_
2019-05-06 09:59:36,975 (7f75537fe700) :  DEBUG (runtime:814) - Found route matching /:/plugins/com.plexapp.system/messaging/function/X0FnZW50U2VydmljZTpVcGRhdGVJbmZv/Y2VyZWFsMQoxCmxpc3QKMApyMAo_/Y2VyZWFsMQo3CmRpY3QKbGlzdApkaWN0Cmxpc3QKbGlzdApsaXN0Cmxpc3QKMgpzMjMKY29tLnBsZXhhcHAuYWdlbnRzLmltZGJzMTAKaWRlbnRpZmllcnIxCnMxMAphZ2VudF9pbmZvMQpyMgoxMApyMwpzMTEKbWVkaWFfdHlwZXNyNApzMTIKYWNjZXB0c19mcm9tbnMxNApmYWxsYmFja19hZ2VudHI1CnMxNApjb250cmlidXRlc190b3I2CnM5Cmxhbmd1YWdlc2IxczIwCnBlcnNpc3Rfc3RvcmVkX2ZpbGVzaTAKczcKdmVyc2lvbmIxczE2CnByaW1hcnlfcHJvdmlkZXJiMXM1CnByZWZzczEwClBsZXggTW92aWVzNApuYW1lMQpzNQpNb3ZpZTEKczI5CmNvbS5wbGV4YXBwLmFnZW50cy5sb2NhbG1lZGlhMQpzMjkKY29tLnBsZXhhcHAuYWdlbnRzLnRoZW1vdmllZGIzMwpzMgplbnMyCnN2czIKZnJzMgplc3MyCm5sczIKZGVzMgppdHMyCmRhczIKYXJzMgpjYXMyCnpoczIKY3NzMgpldHMyCmZpczIKZWxzMgpoZXMyCmhpczIKaHVzMgppZHMyCmphczIKa29zMgpsdnMyCm5vczIKZmFzMgpwbHMyCnB0czIKcm9zMgpydXMyCnNrczIKdGhzMgp0cnMyCnVrczIKdmlyMAo_
2019-05-06 09:59:36,975 (7f75537fe700) :  INFO (agentservice:167) - Receiving agent info from com.plexapp.agents.imdb: [{'media_types': ['Movie'], 'primary_provider': True, 'fallback_agent': None, 'contributes_to': ['com.plexapp.agents.themoviedb'], 'languages': ['en', 'sv', 'fr', 'es', 'nl', 'de', 'it', 'da', 'ar', 'ca', 'zh', 'cs', 'et', 'fi', 'el', 'he', 'hi', 'hu', 'id', 'ja', 'ko', 'lv', 'no', 'fa', 'pl', 'pt', 'ro', 'ru', 'sk', 'th', 'tr', 'uk', 'vi'], 'persist_stored_files': True, 'version': 0, 'accepts_from': ['com.plexapp.agents.localmedia'], 'prefs': True, 'name': 'Plex Movie'}]
2019-05-06 09:59:36,978 (7f75537fe700) :  DEBUG (runtime:924) - Response: [200] str, 16 bytes
2019-05-06 09:59:41,985 (7f7553fff700) :  INFO (datakit:131) - Saved the dictionary file
2019-05-06 09:59:46,240 (7f75527fc700) :  CRITICAL (runtime:1299) - Exception getting hosted resource hashes (most recent call last):
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-ad6e39743/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/components/runtime.py", line 1291, in get_resource_hashes
    json = self._core.networking.http_request("http://resources-cdn.plexapp.com/hashes.json", timeout=5).content
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-ad6e39743/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/components/networking.py", line 265, in content
    return self.__str__()
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-ad6e39743/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/components/networking.py", line 243, in __str__
    self.load()
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-ad6e39743/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/components/networking.py", line 181, in load
    f = self._opener.open(req, timeout=self._timeout)
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-ad6e39743/Framework.bundle/Contents/Resources/Platforms/Shared/Libraries/urllib2_new.py", line 438, in open
    response = self._open(req, data)
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-ad6e39743/Framework.bundle/Contents/Resources/Platforms/Shared/Libraries/urllib2_new.py", line 456, in _open
    '_open', req)
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-ad6e39743/Framework.bundle/Contents/Resources/Platforms/Shared/Libraries/urllib2_new.py", line 416, in _call_chain
    result = func(*args)
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-ad6e39743/Framework.bundle/Contents/Resources/Platforms/Shared/Libraries/urllib2_new.py", line 1217, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-ad6e39743/Framework.bundle/Contents/Resources/Platforms/Shared/Libraries/urllib2_new.py", line 1192, in do_open
    raise URLError(err)
URLError: <urlopen error [Errno -3] Temporary failure in name resolution>

2019-05-06 09:59:46,242 (7f75527fc700) :  DEBUG (runtime:924) - Response: [200] str, 13276 bytes
2019-05-06 14:32:58,672 (7f75595fa700) :  DEBUG (runtime:1156) - Starting timed thread named 'auto_update_thread'
2019-05-06 14:32:58,678 (7f75595fa700) :  INFO (storeservice:356) - Starting automatic update check
2019-05-06 14:32:58,683 (7f75595fa700) :  DEBUG (runtime:1117) - Created a thread named 'remove_unavailable_agents'
2019-05-06 14:32:58,696 (7f75595fa700) :  DEBUG (networking:166) - Requesting 'https://plugins.plex.tv/apps/all.json?frameworkVersion=2.6.3&machineIdentifier=3e7b7fe94c75e0be03ba9545393f1604f763ce60&os=Linux&osVersion=4.9.0-8-amd64&cpu=i386&serverVersion=1.15.3.876-ad6e39743&systemRevision=ad6e397'
2019-05-06 14:33:03,714 (7f7553fff700) :  INFO (datakit:131) - Saved the dictionary file
2019-05-06 14:33:18,722 (7f75595fa700) :  INFO (storeservice:509) - Failed to fetch Plex Online data - the store probably won't work
2019-05-06 14:33:18,724 (7f75595fa700) :  CRITICAL (storeservice:510) - Error info (most recent call last):
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-ad6e39743/System.bundle/Contents/Code/storeservice.py", line 495, in update
    log_msg = "Updated information for plug-in '%s' (class: %s) to a stable version"
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-ad6e39743/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/api/parsekit.py", line 145, in ObjectFromURL
    method=method,
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-ad6e39743/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/api/networkkit.py", line 67, in _http_request
    req = self._core.networking.http_request(url, *args, **kwargs)
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-ad6e39743/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/components/networking.py", line 370, in http_request
    return HTTPRequest(self._core, url, data, h, url_cache, encoding, errors, timeout, immediate, sleep, opener, follow_redirects, method)
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-ad6e39743/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/components/networking.py", line 141, in __init__
    self.load()
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-ad6e39743/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/components/networking.py", line 181, in load
    f = self._opener.open(req, timeout=self._timeout)
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-ad6e39743/Framework.bundle/Contents/Resources/Platforms/Shared/Libraries/urllib2_new.py", line 438, in open
    response = self._open(req, data)
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-ad6e39743/Framework.bundle/Contents/Resources/Platforms/Shared/Libraries/urllib2_new.py", line 456, in _open
    '_open', req)
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-ad6e39743/Framework.bundle/Contents/Resources/Platforms/Shared/Libraries/urllib2_new.py", line 416, in _call_chain
    result = func(*args)
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-ad6e39743/Framework.bundle/Contents/Resources/Platforms/Shared/Libraries/urllib2_new.py", line 1225, in https_open
    return self.do_open(httplib.HTTPSConnection, req)
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-ad6e39743/Framework.bundle/Contents/Resources/Platforms/Shared/Libraries/urllib2_new.py", line 1192, in do_open
    raise URLError(err)
URLError: <urlopen error [Errno -3] Temporary failure in name resolution>

2019-05-06 14:33:18,727 (7f75595fa700) :  INFO (storeservice:531) - 'Services' plug-in [com.plexapp.system.services] is up to date (62fcf1f)
2019-05-06 14:33:18,727 (7f75595fa700) :  INFO (storeservice:362) - All plug-ins are up to date
2019-05-06 14:33:18,728 (7f75595fa700) :  DEBUG (runtime:1150) - Scheduled a timed thread named 'auto_update_thread'
2019-05-06 19:03:10,730 (7f7553fff700) :  DEBUG (runtime:1156) - Starting timed thread named 'auto_update_thread'
2019-05-06 19:03:10,735 (7f7553fff700) :  INFO (storeservice:356) - Starting automatic update check
2019-05-06 19:03:10,741 (7f7553fff700) :  DEBUG (runtime:1117) - Created a thread named 'remove_unavailable_agents'
2019-05-06 19:03:10,754 (7f7553fff700) :  DEBUG (networking:166) - Requesting 'https://plugins.plex.tv/apps/all.json?frameworkVersion=2.6.3&machineIdentifier=3e7b7fe94c75e0be03ba9545393f1604f763ce60&os=Linux&osVersion=4.9.0-8-amd64&cpu=i386&serverVersion=1.15.3.876-ad6e39743&systemRevision=ad6e397'
2019-05-06 19:03:15,762 (7f75527fc700) :  INFO (datakit:131) - Saved the dictionary file
2019-05-06 19:03:30,781 (7f7553fff700) :  INFO (storeservice:509) - Failed to fetch Plex Online data - the store probably won't work
2019-05-06 19:03:30,782 (7f7553fff700) :  CRITICAL (storeservice:510) - Error info (most recent call last):
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-ad6e39743/System.bundle/Contents/Code/storeservice.py", line 495, in update
    log_msg = "Updated information for plug-in '%s' (class: %s) to a stable version"
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-ad6e39743/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/api/parsekit.py", line 145, in ObjectFromURL
    method=method,
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-ad6e39743/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/api/networkkit.py", line 67, in _http_request
    req = self._core.networking.http_request(url, *args, **kwargs)
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-ad6e39743/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/components/networking.py", line 370, in http_request
    return HTTPRequest(self._core, url, data, h, url_cache, encoding, errors, timeout, immediate, sleep, opener, follow_redirects, method)
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-ad6e39743/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/components/networking.py", line 141, in __init__
    self.load()
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-ad6e39743/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/components/networking.py", line 181, in load
    f = self._opener.open(req, timeout=self._timeout)
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-ad6e39743/Framework.bundle/Contents/Resources/Platforms/Shared/Libraries/urllib2_new.py", line 438, in open
    response = self._open(req, data)
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-ad6e39743/Framework.bundle/Contents/Resources/Platforms/Shared/Libraries/urllib2_new.py", line 456, in _open
    '_open', req)
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-ad6e39743/Framework.bundle/Contents/Resources/Platforms/Shared/Libraries/urllib2_new.py", line 416, in _call_chain
    result = func(*args)
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-ad6e39743/Framework.bundle/Contents/Resources/Platforms/Shared/Libraries/urllib2_new.py", line 1225, in https_open
    return self.do_open(httplib.HTTPSConnection, req)
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-ad6e39743/Framework.bundle/Contents/Resources/Platforms/Shared/Libraries/urllib2_new.py", line 1192, in do_open
    raise URLError(err)
URLError: <urlopen error [Errno -3] Temporary failure in name resolution>

2019-05-06 19:03:30,783 (7f7553fff700) :  INFO (storeservice:531) - 'Services' plug-in [com.plexapp.system.services] is up to date (62fcf1f)
2019-05-06 19:03:30,783 (7f7553fff700) :  INFO (storeservice:362) - All plug-ins are up to date
2019-05-06 19:03:30,784 (7f7553fff700) :  DEBUG (runtime:1150) - Scheduled a timed thread named 'auto_update_thread'
2019-05-07 01:16:06,788 (7f75527fc700) :  DEBUG (runtime:1156) - Starting timed thread named 'auto_update_thread'
2019-05-07 01:16:06,794 (7f75527fc700) :  INFO (storeservice:356) - Starting automatic update check
2019-05-07 01:16:06,798 (7f75527fc700) :  DEBUG (runtime:1117) - Created a thread named 'remove_unavailable_agents'
2019-05-07 01:16:06,811 (7f75527fc700) :  DEBUG (networking:166) - Requesting 'https://plugins.plex.tv/apps/all.json?frameworkVersion=2.6.3&machineIdentifier=3e7b7fe94c75e0be03ba9545393f1604f763ce60&os=Linux&osVersion=4.9.0-8-amd64&cpu=i386&serverVersion=1.15.3.876-ad6e39743&systemRevision=ad6e397'
2019-05-07 01:16:11,841 (7f75595fa700) :  INFO (datakit:131) - Saved the dictionary file
2019-05-07 01:16:26,833 (7f75527fc700) :  INFO (storeservice:509) - Failed to fetch Plex Online data - the store probably won't work
2019-05-07 01:16:26,835 (7f75527fc700) :  CRITICAL (storeservice:510) - Error info (most recent call last):
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-ad6e39743/System.bundle/Contents/Code/storeservice.py", line 495, in update
    log_msg = "Updated information for plug-in '%s' (class: %s) to a stable version"
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-ad6e39743/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/api/parsekit.py", line 145, in ObjectFromURL
    method=method,
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-ad6e39743/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/api/networkkit.py", line 67, in _http_request
    req = self._core.networking.http_request(url, *args, **kwargs)
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-ad6e39743/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/components/networking.py", line 370, in http_request
    return HTTPRequest(self._core, url, data, h, url_cache, encoding, errors, timeout, immediate, sleep, opener, follow_redirects, method)
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-ad6e39743/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/components/networking.py", line 141, in __init__
    self.load()
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-ad6e39743/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/components/networking.py", line 181, in load
    f = self._opener.open(req, timeout=self._timeout)
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-ad6e39743/Framework.bundle/Contents/Resources/Platforms/Shared/Libraries/urllib2_new.py", line 438, in open
    response = self._open(req, data)
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-ad6e39743/Framework.bundle/Contents/Resources/Platforms/Shared/Libraries/urllib2_new.py", line 456, in _open
    '_open', req)
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-ad6e39743/Framework.bundle/Contents/Resources/Platforms/Shared/Libraries/urllib2_new.py", line 416, in _call_chain
    result = func(*args)
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-ad6e39743/Framework.bundle/Contents/Resources/Platforms/Shared/Libraries/urllib2_new.py", line 1225, in https_open
    return self.do_open(httplib.HTTPSConnection, req)
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-ad6e39743/Framework.bundle/Contents/Resources/Platforms/Shared/Libraries/urllib2_new.py", line 1192, in do_open
    raise URLError(err)
URLError: <urlopen error [Errno -3] Temporary failure in name resolution>

2019-05-07 01:16:26,838 (7f75527fc700) :  INFO (storeservice:531) - 'Services' plug-in [com.plexapp.system.services] is up to date (62fcf1f)
2019-05-07 01:16:26,838 (7f75527fc700) :  INFO (storeservice:362) - All plug-ins are up to date
2019-05-07 01:16:26,839 (7f75527fc700) :  DEBUG (runtime:1150) - Scheduled a timed thread named 'auto_update_thread'
